import { analyticsPeriodSchema, dataQualityReportSchema, metricSnapshotInputSchema, normalizedMetricSchema, performanceInsightSchema, performanceScoreSchema, platformMetricInputSchema, type AnalyticsFilter, type AnalyticsPeriod, type DataQualityReport, type DerivedKpi, type MetricAvailability, type MetricSnapshotInput, type NormalizedMetric, type PerformanceInsight, type PerformanceScore, type PlatformMetricInput } from "@casapratica/domain";
export interface StoredMetric extends NormalizedMetric { id:string; createdAt:Date }
export interface StoredConversion { id:string; source:string; publicationId:string|null; productId:string|null; occurredAt:Date; amount:number|null; commission:number|null; currency:string|null }
export interface StoredExperiment { id:string; name:string; hypothesis:string; status:string; startsAt:Date|null; endsAt:Date|null; configuration:Readonly<Record<string,unknown>>; result:Readonly<Record<string,unknown>>|null }
export interface AnalyticsRepository { appendMetrics(w:string,m:readonly NormalizedMetric[]):Promise<number>; listMetrics(w:string,p:AnalyticsPeriod,f?:AnalyticsFilter):Promise<readonly StoredMetric[]>; listConversions(w:string,p:AnalyticsPeriod,f?:AnalyticsFilter):Promise<readonly StoredConversion[]>; listExperiments(w:string,p:AnalyticsPeriod):Promise<readonly StoredExperiment[]> }
export interface AnalyticsProvider { source:PlatformMetricInput["source"]; fetch(p:AnalyticsPeriod):Promise<readonly PlatformMetricInput[]> }
export interface PerformanceAnalysis { classification:"WINNER"|"PROMISING"|"NEUTRAL"|"WEAK"|"INSUFFICIENT_DATA"; score:PerformanceScore; metrics:Readonly<Record<string,number|null>>; kpis:Readonly<Record<string,DerivedKpi>>; insights:readonly PerformanceInsight[]; warnings:readonly string[] }
const names=["impressions","reach","saves","pinClicks","outboundClicks","reactions","comments","shares","clicks","videoViews","engagement","affiliateClicks","conversions","sales","revenue","commission"] as const;
const round=(n:number,p=4)=>Number(n.toFixed(p));
export function normalizeMetric(i:PlatformMetricInput,at=new Date()):NormalizedMetric { return normalizedMetricSchema.parse({...platformMetricInputSchema.parse(i),normalizedAt:at}); }
export function calculateRate(nn:string,n:number|null,dn:string,d:number|null,missing:MetricAvailability="unavailable"):DerivedKpi { if(d===null)return {value:null,availability:missing,numerator:nn,denominator:dn,explanation:`${dn} indisponível; taxa não calculada.`}; if(d===0)return {value:null,availability:"not_applicable",numerator:nn,denominator:dn,explanation:`${dn} é zero; divisão não realizada.`}; if(n===null)return {value:null,availability:missing,numerator:nn,denominator:dn,explanation:`${nn} indisponível; taxa não calculada.`}; const value=round(n/d); return {value,availability:value===0?"zero":"available",numerator:nn,denominator:dn,explanation:`${nn} / ${dn}.`}; }
const vals=(ms:readonly StoredMetric[],n:string)=>ms.filter(m=>m.metricName===n&&["available","zero"].includes(m.availability)&&m.value!==null).map(m=>m.value as number);
const sum=(ms:readonly StoredMetric[],n:string)=>{const v=vals(ms,n);return v.length?v.reduce((a,b)=>a+b,0):null};
const map=(ms:readonly StoredMetric[])=>Object.fromEntries(names.map(n=>[n,sum(ms,n)])) as Record<typeof names[number],number|null>;
const median=(a:readonly number[])=>{if(!a.length)return null;const s=[...a].sort((x,y)=>x-y),i=Math.floor(s.length/2);return s.length%2?s[i]!:(s[i-1]!+s[i]!)/2};
export function calculatePerformanceScore(ms:readonly StoredMetric[],bench:readonly StoredMetric[]=ms):PerformanceScore { const totals=map(ms), signals=["outboundClicks","clicks","saves","engagement","conversions","commission"] as const,components:Record<string,number>={},availableSignals:string[]=[],missingSignals:string[]=[]; for(const n of signals){const v=totals[n],base=median(vals(bench,n));if(v===null||base===null||base===0)missingSignals.push(n);else{availableSignals.push(n);components[n]=round(Math.min(100,v/base*50),2)}}const c=Object.values(components),score=c.length?round(c.reduce((a,b)=>a+b,0)/c.length,2):null,sample=Math.max(totals.impressions??0,totals.reach??0),confidence=round(Math.min(1,sample/1000)*(availableSignals.length/signals.length));return performanceScoreSchema.parse({score,confidence,availableSignals,missingSignals,components,explanation:score===null?"Performance Score indisponível: sinais comparáveis insuficientes.":`Score relativo com ${availableSignals.length} sinais; separado do Product Score.`}); }
const classify=(s:PerformanceScore,m:Record<string,number|null>)=>{if(Math.max(m.impressions??0,m.reach??0)<100||s.confidence<.25||s.score===null)return "INSUFFICIENT_DATA" as const;if(s.score>=70)return "WINNER" as const;if(s.score>=55)return "PROMISING" as const;if(s.score<35)return "WEAK" as const;return "NEUTRAL" as const};
export function detectSaturation(ms:readonly StoredMetric[]):PerformanceInsight|null { const periods=[...new Set(ms.map(m=>m.periodEnd.toISOString()))].sort(),ctrs=periods.map(p=>{const g=ms.filter(m=>m.periodEnd.toISOString()===p);return calculateRate("clicks",sum(g,"outboundClicks")??sum(g,"clicks"),"impressions",sum(g,"impressions")).value}).filter((v):v is number=>v!==null);if(ctrs.length<3||ctrs.at(-3)!<=ctrs.at(-2)!||ctrs.at(-2)!<=ctrs.at(-1)!||ctrs.at(-3)===0)return null;const decline=(ctrs.at(-3)!-ctrs.at(-1)!)/ctrs.at(-3)!;if(decline<.15)return null;return performanceInsightSchema.parse({type:"SATURATION",severity:"warning",entityType:"series",entityId:null,title:"Possível saturação",explanation:"CTR caiu progressivamente em três períodos; é um sinal, não uma ordem automática.",evidence:ctrs.slice(-3).map(v=>`CTR ${round(v*100,2)}%`),confidence:Math.min(.85,.5+decline),recommendedAction:"Testar novo criativo antes de reduzir exposição."}); }
function analyze(ms:readonly StoredMetric[],bench:readonly StoredMetric[]):PerformanceAnalysis { const metrics=map(ms),score=calculatePerformanceScore(ms,bench),classification=classify(score,metrics),den=metrics.impressions??metrics.reach,clicks=metrics.outboundClicks??metrics.clicks,kpis={ctr:calculateRate("clicks",clicks,"impressions/reach",den),saveRate:calculateRate("saves",metrics.saves,"impressions",metrics.impressions),engagementRate:calculateRate("engagement",metrics.engagement,metrics.impressions!==null?"impressions":"reach",den),conversionRate:calculateRate("conversions",metrics.conversions,"affiliateClicks",metrics.affiliateClicks,"unknown"),revenuePerClick:calculateRate("revenue",metrics.revenue,"affiliateClicks",metrics.affiliateClicks,"unknown"),commissionPerClick:calculateRate("commission",metrics.commission,"affiliateClicks",metrics.affiliateClicks,"unknown")},insights:PerformanceInsight[]=[];if(classification==="WINNER")insights.push(performanceInsightSchema.parse({type:"WINNER",severity:"info",entityType:"selection",entityId:null,title:"Desempenho vencedor",explanation:"Acima das referências com amostra mínima.",evidence:[`score ${score.score}`],confidence:score.confidence,recommendedAction:"Validar com novo teste antes de mudar estratégia."}));if(classification==="WEAK")insights.push(performanceInsightSchema.parse({type:"UNDERPERFORMER",severity:"warning",entityType:"selection",entityId:null,title:"Desempenho fraco",explanation:"Pede diagnóstico; não prova que o produto é ruim.",evidence:[`score ${score.score}`],confidence:score.confidence,recommendedAction:"Executar um segundo teste com abordagem diferente."}));const sat=detectSaturation(ms);if(sat)insights.push(sat);return {classification,score,metrics,kpis,insights,warnings:ms.length?[]:["Dados insuficientes"]}; }
export function compareCreativePerformance(groups:Readonly<Record<string,readonly StoredMetric[]>>){const bench=Object.values(groups).flat(),variants=Object.entries(groups).map(([creativeAssetId,ms])=>({creativeAssetId,analysis:analyze(ms,bench)})),eligible=variants.filter(v=>v.analysis.classification!=="INSUFFICIENT_DATA"&&v.analysis.score.score!==null).sort((a,b)=>(b.analysis.score.score??0)-(a.analysis.score.score??0));return {variants,winner:eligible.length>=2?eligible[0]?.creativeAssetId??null:null,confidence:eligible.length>=2?Math.min(...eligible.map(v=>v.analysis.score.confidence)):0,explanation:eligible.length>=2?"Comparação com amostra mínima.":"Dados insuficientes para declarar criativo vencedor."};}
export class PerformanceIntelligenceService {
 constructor(private readonly repo:AnalyticsRepository,private readonly providers:Readonly<Partial<Record<PlatformMetricInput["source"],AnalyticsProvider>>>={}){}
 async importMetrics(w:string,input:MetricSnapshotInput){const p=metricSnapshotInputSchema.parse(input),ms=p.metrics.map(m=>normalizeMetric(m,p.importedAt));return {imported:await this.repo.appendMetrics(w,ms),sourceCount:new Set(ms.map(m=>m.source)).size}}
 async importProvider(w:string,s:PlatformMetricInput["source"],p:AnalyticsPeriod){const provider=this.providers[s];if(!provider)throw new Error("analytics_provider_not_configured");return this.importMetrics(w,{metrics:[...await provider.fetch(analyticsPeriodSchema.parse(p))],importedAt:new Date()})}
 async overview(w:string,p:AnalyticsPeriod,f:AnalyticsFilter={}){const period=analyticsPeriodSchema.parse(p),ms=await this.repo.listMetrics(w,period,f),cs=await this.repo.listConversions(w,period,f),quality=this.quality(ms,period);return {period,dataCoverage:quality.coverage,...analyze(ms,ms),conversionRecords:cs.length,conversionTotals:{sales:cs.length,revenue:cs.some(c=>c.amount!==null)?cs.reduce((t,c)=>t+(c.amount??0),0):null,commission:cs.some(c=>c.commission!==null)?cs.reduce((t,c)=>t+(c.commission??0),0):null},dataQuality:quality,message:ms.length?null:"Dados insuficientes"}}
 product(w:string,id:string,p:AnalyticsPeriod){return this.overview(w,p,{productId:id})} category(w:string,id:string,p:AnalyticsPeriod){return this.overview(w,p,{categoryId:id})} platform(w:string,id:"pinterest"|"facebook"|"business",p:AnalyticsPeriod){return this.overview(w,p,{platform:id})}
 async creativeComparison(w:string,ids:readonly string[],p:AnalyticsPeriod){const entries=await Promise.all([...new Set(ids)].map(async id=>[id,await this.repo.listMetrics(w,p,{creativeAssetId:id})] as const));return compareCreativePerformance(Object.fromEntries(entries))}
 async insights(w:string,p:AnalyticsPeriod){return (await this.overview(w,p)).insights} async dataQuality(w:string,p:AnalyticsPeriod){const period=analyticsPeriodSchema.parse(p);return this.quality(await this.repo.listMetrics(w,period),period)}
 async group(w:string,p:AnalyticsPeriod,key:"productId"|"categoryId"|"platform"){const period=analyticsPeriodSchema.parse(p),ms=await this.repo.listMetrics(w,period),groups=new Map<string,StoredMetric[]>();for(const m of ms){const id=key==="platform"?m.platform:m[key];if(id)groups.set(id,[...(groups.get(id)??[]),m])}return [...groups.entries()].map(([id,g])=>({id,...analyze(g,ms)})).sort((a,b)=>(b.score.score??-1)-(a.score.score??-1))}
 async daily(w:string,p:AnalyticsPeriod){const [o,products,categories,platforms]=await Promise.all([this.overview(w,p),this.group(w,p,"productId"),this.group(w,p,"categoryId"),this.group(w,p,"platform")]);return {period:o.period,dataCoverage:o.dataCoverage,topProducts:products.filter(x=>x.classification==="WINNER"),promisingProducts:products.filter(x=>x.classification==="PROMISING"),weakProducts:products.filter(x=>x.classification==="WEAK"),topCategories:categories.slice(0,5),platformSummary:platforms,insights:o.insights,warnings:o.warnings,recommendations:o.insights.map(i=>i.recommendedAction),message:o.message}}
 async weekly(w:string,p:AnalyticsPeriod){const [overview,experiments,products,categories,platforms]=await Promise.all([this.overview(w,p),this.repo.listExperiments(w,p),this.group(w,p,"productId"),this.group(w,p,"categoryId"),this.group(w,p,"platform")]);return {period:overview.period,businessSummary:overview,platformPerformance:platforms,productPerformance:products,categoryPerformance:categories,experiments,insights:overview.insights,recommendations:overview.insights.map(i=>i.recommendedAction),dataQuality:overview.dataQuality,message:overview.message}}
 async winners(w:string,p:AnalyticsPeriod){return (await this.group(w,p,"productId")).filter(x=>["WINNER","PROMISING"].includes(x.classification))} async underperformers(w:string,p:AnalyticsPeriod){return (await this.group(w,p,"productId")).filter(x=>x.classification==="WEAK")}
 private quality(ms:readonly StoredMetric[],p:AnalyticsPeriod):DataQualityReport {const byAvailability={available:0,zero:0,not_applicable:0,unknown:0,unavailable:0};for(const m of ms)byAvailability[m.availability]++;const available=byAvailability.available+byAvailability.zero,duplicates=ms.length-new Set(ms.map(m=>`${m.source}:${m.metricName}:${m.externalEntityId}:${m.periodStart.toISOString()}:${m.periodEnd.toISOString()}`)).size,fresh=ms.length?Math.max(...ms.map(m=>m.capturedAt.getTime())):null,partialPeriod=p.end>new Date();return dataQualityReportSchema.parse({coverage:ms.length?round(available/ms.length):0,availableMetrics:available,unavailableMetrics:ms.length-available,byAvailability,duplicates,partialPeriod,freshestAt:fresh?new Date(fresh):null,staleSource:fresh===null||Date.now()-fresh>604800000,anomalies:this.anomalies(ms),warnings:[...(!ms.length?["Dados insuficientes"]:[]),...(duplicates?["Possíveis snapshots duplicados"]:[]),...(partialPeriod?["Período ainda não concluído"]:[])]})}
 private anomalies(ms:readonly StoredMetric[]){const g=new Map<string,number[]>();for(const m of ms)if(m.value!==null&&["available","zero"].includes(m.availability))g.set(m.metricName,[...(g.get(m.metricName)??[]),m.value]);return [...g.entries()].flatMap(([metricName,v])=>{if(v.length<4)return [];const baseline=median(v.slice(0,-1)),latest=v.at(-1)!;if(baseline===null||baseline===0||Math.abs(latest-baseline)/baseline<1)return [];return [{metricName:metricName as typeof names[number],type:latest>baseline?"unusual_spike" as const:"unusual_drop" as const,latest,baseline,confidence:.6}]})}
}
