import { describe, expect, it } from "vitest";
import { ContentEngine, type ContentHistoryItem, type ContentRepository, type ContentVariantDraft, type ProductContentFacts, type SavedContent } from "./content-engine.js";

class MemoryContentRepository implements ContentRepository {
  history: ContentHistoryItem[] = [];
  product: ProductContentFacts | null = { id: "p1", workspaceId: "w1", name: "Organizador de cozinha", description: null, affiliateUrl: "https://example.com/afiliado", rating: 4.8, reviewCount: 120, currentPrice: 89.9, priceCheckedAt: new Date() };
  async getProductFacts() { return this.product; } async listProductContent() { return this.history; } async listRecentContent() { return this.history; }
  async create(_workspaceId: string, productId: string | null, _title: string, _body: string, variants: readonly ContentVariantDraft[]): Promise<SavedContent> { const saved = variants.map((value, index) => ({ id: `v${index}`, productId, platform: value.platform, title: value.title, body: value.body, metadata: value.metadata, createdAt: new Date() })); this.history.push(...saved); return { id: "c1", productId, status: "draft", variants: saved }; }
  async createVariant(_workspaceId: string, _contentId: string, value: ContentVariantDraft) { const saved = { id: "new", productId: null, platform: value.platform, title: value.title, body: value.body, metadata: value.metadata, createdAt: new Date() }; this.history.push(saved); return saved; }
}
describe("ContentEngine", () => {
  it("gera 2-3 Pins realmente diferentes, estruturados e sem preço no copy", async () => { const engine = new ContentEngine(new MemoryContentRepository()); const result = await engine.generateProduct({ workspaceId: "w1", productId: "p1", platforms: ["pinterest"], variants: 3 }); expect(new Set(result.variants.map(value => value.body)).size).toBe(3); expect(result.variants.every(value => value.metadata.contentAngle)).toBe(true); expect(result.variants.map(value => value.body).join(" ")).not.toContain("89"); expect(result.status).toBe("draft"); });
  it("gera Facebook com link somente no comentário e disclosure", async () => { const engine = new ContentEngine(new MemoryContentRepository()); const [variant] = (await engine.generateProduct({ workspaceId: "w1", productId: "p1", platforms: ["facebook"], variants: 1 })).variants; expect(variant?.metadata.linkPlacement).toBe("COMMENT"); expect(variant?.body).not.toContain("https://"); expect(variant?.metadata.comment).toMatchObject({ affiliateUrl: "https://example.com/afiliado" }); expect(String(variant?.metadata.affiliateDisclosure)).toMatch(/comissão/); });
  it("usa NONE e não cria comentário quando produto não tem affiliateUrl", async () => { const repository = new MemoryContentRepository(); repository.product = { ...repository.product!, affiliateUrl: null }; const [variant] = (await new ContentEngine(repository).generateProduct({ workspaceId: "w1", productId: "p1", platforms: ["facebook"], variants: 1 })).variants; expect(variant?.metadata.linkPlacement).toBe("NONE"); expect(variant?.metadata.comment).toBeNull(); });
  it("gera conteúdo útil e sazonal sem produto nem link", async () => { const result = await new ContentEngine(new MemoryContentRepository()).generateUtility({ workspaceId: "w1", platform: "pinterest", topic: "organizar cozinha pequena", seasonalContext: "organização de começo de ano" }); expect(result.productId).toBeNull(); expect(result.variants[0]?.metadata.linkPlacement).toBe("NONE"); expect(result.variants[0]?.metadata.seasonalContext).toBe("organização de começo de ano"); });
  it("consulta histórico e bloqueia duplicação", async () => { const repository = new MemoryContentRepository(), engine = new ContentEngine(repository); await engine.generateUtility({ workspaceId: "w1", platform: "facebook", topic: "checklist da casa" }); await expect(engine.generateUtility({ workspaceId: "w1", platform: "facebook", topic: "checklist da casa" })).rejects.toThrow("duplicate_content"); });
  it("não inventa prova social quando rating está ausente", async () => { const repository = new MemoryContentRepository(); repository.product = { ...repository.product!, rating: null, reviewCount: null }; const result = await new ContentEngine(repository).generateProduct({ workspaceId: "w1", productId: "p1", platforms: ["pinterest"], variants: 1, angles: ["social_proof"] }); expect(result.variants[0]?.body).not.toMatch(/avaliação confirmada|bem avaliado/i); });
});
