import { createHash } from "node:crypto";
import { DEFAULT_BRAND_KIT, creativeOutputSchema, creativeRequestSchema, creativeValidationResultSchema, creativeVariantSchema, productImageAnalysisSchema, productImageSelectionSchema, type BrandKit, type CreativeOutput, type CreativeRequest, type CreativeValidationResult, type CreativeVariant, type ProductImageAnalysis, type ProductImageCandidate } from "@casapratica/domain";
import type { ImageCompositionProvider, ImageGenerationProvider } from "@casapratica/integrations";
import { DEFAULT_CREATIVE_PRICE_CONFIG, isPriceFresh, type CreativePriceConfig } from "./creative-config.js";

export interface CreativeStudioRepository { getRequest(workspaceId: string, productId: string, input: { contentId: string; platform: "pinterest" | "facebook"; format: CreativeRequest["format"]; template: CreativeRequest["template"]; variantCount: number }): Promise<CreativeRequest>; saveAsset(workspaceId: string, request: CreativeRequest, rendered: { storageKey: string; width: number; height: number; mimeType: string }, output: CreativeOutput): Promise<CreativeOutput>; listAssets(workspaceId: string, productId: string): Promise<readonly unknown[]> }
export class ProductImageAnalyzer { analyze(image: ProductImageCandidate, format: CreativeRequest["format"]): ProductImageAnalysis { const target = format === "PINTEREST_2_3" ? 2 / 3 : format === "FACEBOOK_4_5" ? 4 / 5 : 1, ratio = image.width / image.height, ratioFit = Math.max(0, 1 - Math.abs(ratio - target) / target), resolution = Math.min(1, Math.min(image.width / 1000, image.height / 1000)), score = Math.round(100 * (.25 * Number(image.productVisible) + .2 * resolution + .12 * ratioFit + .12 * image.focusScore + .1 * image.lightingScore + .1 * (1 - image.visualNoiseScore) + .11 * image.overlaySpaceScore - (image.hasConflictingText ? .15 : 0))); const strengths = [image.productVisible && "Produto visível", resolution >= 1 && "Resolução adequada", image.overlaySpaceScore >= .6 && "Espaço para overlay", image.usageDemonstration && "Demonstração de uso"].filter((x): x is string => Boolean(x)); const risks = [resolution < .7 && "Resolução insuficiente", image.hasConflictingText && "Texto conflitante", image.visualNoiseScore > .6 && "Ruído visual", !image.productVisible && "Produto não identificado"].filter((x): x is string => Boolean(x)); return productImageAnalysisSchema.parse({ imageUrl: image.imageUrl, score: Math.max(0, score), strengths, risks, selectionReason: `Score determinístico por visibilidade, resolução, proporção, foco, iluminação, ruído e espaço de overlay.` }); } }
export class ProductImageSelector { constructor(private readonly minimumScore = 60) {} select(analyses: readonly ProductImageAnalysis[]) { const ranked = [...analyses].sort((a, b) => b.score - a.score || a.imageUrl.localeCompare(b.imageUrl)); const primaryImage = ranked[0]?.score !== undefined && ranked[0].score >= this.minimumScore ? ranked[0] : null; return productImageSelectionSchema.parse({ primaryImage, alternateImages: primaryImage ? ranked.slice(1, 3) : [], creativeStatus: primaryImage ? "DRAFT" : "NEEDS_REVIEW", reason: primaryImage ? "Maior score acima do mínimo configurado." : "Nenhuma imagem atingiu a qualidade mínima; revisão humana necessária." }); } }
export class CreativeValidator { validate(request: CreativeRequest, selection: ReturnType<ProductImageSelector["select"]>, overlays: CreativeOutput["overlays"], priceFresh: boolean): CreativeValidationResult { const errors: string[] = []; if (!selection.primaryImage) errors.push("image_missing_or_invalid"); if (!request.productId || !request.productName) errors.push("product_identification_required"); if (request.confirmedFacts.length > 2) errors.push("too_many_product_facts"); if (overlays.some(value => value.text.length > 80)) errors.push("excessive_overlay_text"); if (overlays.some(value => !value.confirmed && value.kind === "FACT")) errors.push("unconfirmed_claim"); if (request.priceRequested && !priceFresh) errors.push("price_refresh_required"); const warnings = selection.primaryImage?.risks ?? []; return creativeValidationResultSchema.parse({ valid: errors.length === 0, errors, warnings }); } }
export class CreativeComposer { layout(request: CreativeRequest) { const [width, height] = request.format === "PINTEREST_2_3" ? [1000, 1500] : request.format === "FACEBOOK_4_5" ? [1080, 1350] : [1080, 1080]; return { template: request.template, width, height, safeCrop: { strategy: "contain" as const, preserveProduct: true as const, criticalAreaCovered: false }, contrastRatio: 7, overlayBackground: true }; } }
export class CreativeStudioService {
  readonly config: CreativePriceConfig;
  constructor(private readonly repository: CreativeStudioRepository, private readonly composition: ImageCompositionProvider, private readonly generation?: ImageGenerationProvider, private readonly brandKit: BrandKit = DEFAULT_BRAND_KIT, config: Partial<CreativePriceConfig> = {}) { this.config = { ...DEFAULT_CREATIVE_PRICE_CONFIG, ...config }; void this.generation; }
  analyze(request: CreativeRequest) { const parsed = creativeRequestSchema.parse(request); return parsed.images.map(image => new ProductImageAnalyzer().analyze(image, parsed.format)); }
  select(request: CreativeRequest) { return new ProductImageSelector().select(this.analyze(request)); }
  validate(request: CreativeRequest) { const output = this.composeOutput(request, null); return output.validation; }
  async preview(request: CreativeRequest) { return this.render(request, true); }
  async render(request: CreativeRequest, preview = false) { const parsed = creativeRequestSchema.parse(request), output = this.composeOutput(parsed, null); if (!output.validation.valid) return output; const key = `${preview ? "previews" : "renders"}/${parsed.productId}-${createHash("sha256").update(JSON.stringify(output.metadata)).digest("hex").slice(0, 12)}.png`; const rendered = await this.composition.compose({ sourcePath: output.primaryImage!.imageUrl, outputKey: key, output, brandKit: this.brandKit }); const complete = creativeOutputSchema.parse({ ...output, previewReference: rendered.storageKey }); return preview ? complete : this.repository.saveAsset(parsed.workspaceId, parsed, rendered, complete); }
  variants(request: CreativeRequest): readonly CreativeVariant[] { const selection = this.select(request); if (!selection.primaryImage) return []; const angles = ["organization", "practicality", "space_saving"] as const, layouts = ["PHOTO_FIRST", "BOTTOM_INFO_PANEL", "TOP_HEADLINE"] as const; return angles.slice(0, request.variantCount).map((contentAngle, index) => creativeVariantSchema.parse({ objective: `Explorar ${contentAngle} com composição distinta`, contentAngle, layout: layouts[index], image: selection.primaryImage!.imageUrl, overlayText: [request.productName, request.confirmedFacts[index] ?? request.safeBenefits[index]].filter((x): x is string => Boolean(x)) })); }
  async request(workspaceId: string, productId: string, input: Parameters<CreativeStudioRepository["getRequest"]>[2]) { return this.repository.getRequest(workspaceId, productId, input); }
  getProductCreatives(workspaceId: string, productId: string) { return this.repository.listAssets(workspaceId, productId); }
  private composeOutput(request: CreativeRequest, previewReference: string | null): CreativeOutput { const selection = this.select(request), layout = new CreativeComposer().layout(request), fresh = isPriceFresh(request.price, request.priceCheckedAt, new Date(), this.config); const overlays = [{ kind: "PRODUCT_NAME" as const, text: request.productName, confirmed: true, x: .06, y: .78, maxWidth: .88 }, ...request.confirmedFacts.slice(0, 2).map((text, index) => ({ kind: "FACT" as const, text, confirmed: true, x: .06, y: .83 + index * .05, maxWidth: .88 })), ...(request.priceRequested && fresh && request.price ? [{ kind: "PRICE" as const, text: request.price.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }), confirmed: true, x: .06, y: .93, maxWidth: .4 }] : []), { kind: "BRAND" as const, text: "CasaPrática", confirmed: true, x: .75, y: .96, maxWidth: .2 }]; const validation = new CreativeValidator().validate(request, selection, overlays, fresh); const status = request.priceRequested && !fresh ? "BLOCKED_FOR_PRICE_REFRESH" : !selection.primaryImage ? "NEEDS_REVIEW" : validation.valid ? "READY" : "DRAFT"; return creativeOutputSchema.parse({ platform: request.platform, size: { width: layout.width, height: layout.height }, primaryImage: selection.primaryImage, layout, overlays, brandPlacement: this.brandKit.brandPlacement, price: request.priceRequested && fresh ? request.price : null, validation, status, previewReference, metadata: { platform: request.platform, template: request.template, width: layout.width, height: layout.height, productId: request.productId, contentId: request.contentId, sourceImage: selection.primaryImage?.imageUrl ?? null, overlays, priceUsed: request.priceRequested && fresh ? request.price : null, priceCheckedAt: request.priceCheckedAt, brandKitVersion: this.brandKit.version, createdAt: new Date().toISOString() } }); }
}
