import { describe, expect, it, vi } from "vitest"; import { CreativeStudioService, ProductImageAnalyzer, ProductImageSelector, type CreativeStudioRepository } from "./creative-studio.js"; import type { CreativeRequest, ProductImageCandidate } from "@casapratica/domain";
const image = (url: string, changes: Partial<ProductImageCandidate> = {}): ProductImageCandidate => ({ imageUrl: url, sourceUrl: url, sourceProvider: "fixture", externalProductId: "ext", imageHash: "hash", width: 1200, height: 1800, mimeType: "image/png", capturedAt: new Date(), assetSource: "MARKETPLACE_PRODUCT_IMAGE", usageStatus: "UNKNOWN", hasConflictingText: false, productVisible: true, focusScore: .9, lightingScore: .9, visualNoiseScore: .1, overlaySpaceScore: .8, usageDemonstration: true, ...changes });
const request = (changes: Partial<CreativeRequest> = {}): CreativeRequest => ({ workspaceId: "w1", productId: "p1", contentId: "c1", platform: "pinterest", format: "PINTEREST_2_3", template: "PHOTO_FIRST", variantCount: 3, productName: "Carrinho Organizador", confirmedFacts: ["4 andares", "Com rodinhas"], safeBenefits: [], price: 58.38, priceCheckedAt: new Date(), priceRequested: true, images: [image("fixture-a")], ...changes });
const repository: CreativeStudioRepository = { getRequest: vi.fn(), saveAsset: vi.fn(async (_w, _r, rendered, output) => ({ ...output, previewReference: rendered.storageKey })), listAssets: vi.fn(async () => []) }; const composition = { compose: vi.fn(async () => ({ storageKey: "preview.png", width: 1000, height: 1500, mimeType: "image/png" as const })) };
describe("Creative Studio", () => {
  it("calcula score e escolhe deterministicamente a melhor imagem", () => { const analyzer = new ProductImageAnalyzer(), good = analyzer.analyze(image("b"), "PINTEREST_2_3"), poor = analyzer.analyze(image("a", { width: 200, height: 200, productVisible: false }), "PINTEREST_2_3"); expect(good.score).toBeGreaterThan(poor.score); expect(new ProductImageSelector().select([poor, good]).primaryImage?.imageUrl).toBe("b"); });
  it("marca NEEDS_REVIEW quando nenhuma imagem é adequada", () => { const analysis = new ProductImageAnalyzer().analyze(image("bad", { width: 100, height: 100, productVisible: false, focusScore: 0, lightingScore: 0, visualNoiseScore: 1, overlaySpaceScore: 0 }), "FACEBOOK_1_1"); expect(new ProductImageSelector().select([analysis]).creativeStatus).toBe("NEEDS_REVIEW"); });
  it("aplica formatos, safe crop, contraste, marca e até dois fatos", async () => { const service = new CreativeStudioService(repository, composition); for (const [format, dimensions] of [["PINTEREST_2_3", [1000, 1500]], ["FACEBOOK_4_5", [1080, 1350]], ["FACEBOOK_1_1", [1080, 1080]]] as const) { const input = request({ format, platform: format === "PINTEREST_2_3" ? "pinterest" : "facebook" }); const validation = service.validate(input); expect(validation.valid).toBe(true); const selection = service.select(input); expect(selection.primaryImage).not.toBeNull(); const preview = await service.preview(input); expect([preview.size.width, preview.size.height]).toEqual(dimensions); expect(preview.overlays.filter(value => value.kind === "FACT")).toHaveLength(2); } expect(service.config.creativePriceFreshnessHours).toBe(24); });
  it("bloqueia preço ausente/desatualizado e não o inventa", async () => { composition.compose.mockClear(); const service = new CreativeStudioService(repository, composition, undefined, undefined, { creativePriceFreshnessHours: 6 }); const missing = await service.preview(request({ price: null })); expect(missing.status).toBe("BLOCKED_FOR_PRICE_REFRESH"); expect(missing.price).toBeNull(); const stale = await service.preview(request({ priceCheckedAt: new Date(Date.now() - 7 * 3_600_000) })); expect(stale.validation.errors).toContain("price_refresh_required"); expect(composition.compose).not.toHaveBeenCalled(); });
  it("rejeita timestamp futuro de preço", async () => { const service = new CreativeStudioService(repository, composition); const result = await service.preview(request({ priceCheckedAt: new Date(Date.now() + 3_600_000) })); expect(result.status).toBe("BLOCKED_FOR_PRICE_REFRESH"); expect(result.price).toBeNull(); });
  it("gera variações com objetivos, angles e layouts distintos", () => { const variants = new CreativeStudioService(repository, composition).variants(request()); expect(new Set(variants.map(value => value.objective)).size).toBe(3); expect(new Set(variants.map(value => value.layout)).size).toBe(3); });
  it("renderiza, persiste metadata e nunca chama gerador", async () => { const generation = { generateBackground: vi.fn() }; const service = new CreativeStudioService(repository, composition, generation); const result = await service.render(request()); expect(result.metadata).toMatchObject({ platform: "pinterest", productId: "p1", contentId: "c1", brandKitVersion: "1" }); expect(repository.saveAsset).toHaveBeenCalledOnce(); expect(generation.generateBackground).not.toHaveBeenCalled(); });
});
