import { describe, expect, it, vi } from "vitest";
import { CASA_PRATICA_CATEGORIES, MERCADO_LIVRE_CATEGORY_MAP, ProductDiscoveryService, calculateOpportunityScore } from "./discovery.js";
describe("ProductDiscoveryService",()=>{
  it("mantém as dez categorias no nicho CasaPrática",()=>{expect(CASA_PRATICA_CATEGORIES).toHaveLength(10);expect(Object.keys(MERCADO_LIVRE_CATEGORY_MAP)).toEqual([...CASA_PRATICA_CATEGORIES])});
  it("calcula OpportunityScore separado do ProductScore",()=>{const score=calculateOpportunityScore({term:"organizador",categoryExternalId:"MLB1574",trendPosition:1,highlightPosition:null,highlightedItemIds:[],rawSourceReferences:[]});expect(score.score).toBe(100);expect(score).not.toHaveProperty("confidence")});
  it("retorna fallback sem fonte e não pesquisa",async()=>{const service=new ProductDiscoveryService(null,null);await expect(service.run("w")).resolves.toMatchObject({connected:false,message:"Mercado Livre ainda não conectado."})});
  it("reutiliza o research engine, resolve categoria e envia highlights ao bulk",async()=>{const source={marketplace:"mercadolivre",resolveCategories:vi.fn(async(terms:readonly string[])=>({[terms[0]!] :"MLB123"})),discover:vi.fn().mockResolvedValue([{term:"mais vendidos",categoryExternalId:"MLB123",trendPosition:null,highlightPosition:1,highlightedItemIds:["MLB1","MLB2"],rawSourceReferences:[]}])},research={research:vi.fn().mockResolvedValue({id:"r",candidates:[]}),listRuns:vi.fn()};const service=new ProductDiscoveryService(source,research as never),result=await service.run("w");expect(result.connected).toBe(true);expect(research.research).toHaveBeenCalledWith(expect.objectContaining({workspaceId:"w",targetCandidates:20,seedExternalIds:["MLB1","MLB2"],opportunityScores:expect.any(Object)}))});
  it("distingue ausência de estrutura, ausência real de resultados e bloqueio",async()=>{for(const [status,expected] of [["no_structured_products","no_structured_products"],["no_results","no_results"],["source_unavailable","source_unavailable"]] as const){const source={marketplace:"public_web",resolveCategories:vi.fn(),discover:vi.fn().mockResolvedValue([]),lastDiscoveryDiagnostics:()=>({status,requests:2,accessibleResponses:status==="source_unavailable"?0:2,failedResponses:status==="source_unavailable"?2:0,noResultResponses:status==="no_results"?2:0,unstructuredResponses:status==="no_structured_products"?2:0,candidates:0})},research={research:vi.fn(),listRuns:vi.fn()};await expect(new ProductDiscoveryService(source,research as never).run("w")).resolves.toMatchObject({status:expected,connected:status!=="source_unavailable",run:null});expect(research.research).not.toHaveBeenCalled()}});
  it("preserva sucesso parcial quando candidatos chegam ao Research",async()=>{const source={marketplace:"public_web",resolveCategories:vi.fn(async(terms:readonly string[])=>({[terms[0]!] :"organização"})),discover:vi.fn().mockResolvedValue([{term:"organizador casa",categoryExternalId:"organização",trendPosition:null,highlightPosition:null,highlightedItemIds:["MLB1"],rawSourceReferences:[]}]),lastDiscoveryDiagnostics:()=>({status:"partial_success" as const,requests:2,accessibleResponses:1,failedResponses:1,noResultResponses:0,unstructuredResponses:0,candidates:1})},research={research:vi.fn().mockResolvedValue({id:"r",candidates:[]}),listRuns:vi.fn()};await expect(new ProductDiscoveryService(source,research as never).run("w")).resolves.toMatchObject({status:"partial_success",connected:true,message:"Pesquisa concluída com cobertura parcial."});expect(research.research).toHaveBeenCalled()});
});
