import { describe, expect, it } from "vitest";
import { FacebookStrategyEngine, type FacebookContentCandidate, type FacebookStrategyRepository } from "./facebook-strategy.js";
import type { FacebookCreativeBrief } from "@casapratica/domain";

const candidate = (id: string, changes: Partial<FacebookContentCandidate> = {}): FacebookContentCandidate => ({ contentId: id, variantId: `v-${id}`, productId: `p-${id}`, contentPillar: "product", contentAngle: "problem_solution", copy: `Falta espaço na cozinha? O organizador ${id} pode ajudar a aproveitar melhor a área disponível.`, cta: "Veja os detalhes no primeiro comentário.", linkPlacement: "COMMENT", preparedComment: { body: "Confira informações e preço atual:", affiliateUrl: "https://example.com/afiliado", affiliateDisclosure: "Este conteúdo contém link de afiliado; podemos receber comissão." }, visualBrief: "Imagem real do produto em contexto doméstico.", affiliateUrl: "https://example.com/afiliado", productName: "Organizador", category: "Cozinha", images: ["https://example.com/image.jpg"], currentPrice: 89, priceCheckedAt: new Date(), createdAt: new Date(), ...changes });
class MemoryRepository implements FacebookStrategyRepository { values: FacebookContentCandidate[] = []; capabilities = { read_pages: true, create_post: true }; strategy = null as Awaited<ReturnType<FacebookStrategyRepository["getStrategy"]>>; prepared = 0; async saveStrategy(_workspace: string, strategy: NonNullable<typeof this.strategy>) { this.strategy = strategy; return strategy; } async getStrategy() { return this.strategy; } async listFacebookContent() { return this.values; } async getFacebookContent(_workspace: string, id: string) { return this.values.find(value => value.contentId === id) ?? null; } async createPublicationPreparation(_workspace: string, _content: FacebookContentCandidate, _brief: FacebookCreativeBrief, commentAction: "MANUAL_REQUIRED" | null) { this.prepared++; return { queueItemId: "q1", status: "approval_required" as const, commentAction }; } async getCapability(_workspace: string, capability: "read_pages" | "create_post") { return { available: this.capabilities[capability], reason: this.capabilities[capability] ? "available" : "missing" }; } }
describe("FacebookStrategyEngine", () => {
  it("gera estratégia semanal com pillars, mix configurável e sazonalidade", async () => { const repository = new MemoryRepository(); repository.values = [candidate("1"), candidate("u", { productId: null, affiliateUrl: null, preparedComment: null, linkPlacement: "NONE", contentPillar: "utility" })]; const strategy = await new FacebookStrategyEngine(repository, undefined, { contentPillarDistribution: { product: 25 } }).createWeeklyStrategy("w1", new Date(), "Natal"); expect(strategy.contentPillarDistribution.product).toBe(25); expect(strategy.productContent).toBe(1); expect(strategy.utilityContent).toBe(1); expect(strategy.futureMetrics).toContain("reach"); });
  it("cria plano diário com mix, teto 20 e redução automática", async () => { const repository = new MemoryRepository(); repository.values = [candidate("1"), candidate("u", { productId: null, affiliateUrl: null, preparedComment: null, linkPlacement: "NONE", contentPillar: "informational" })]; const plan = await new FacebookStrategyEngine(repository).createDailyPlan("w1", new Date(), 20); expect(plan.suggestedPosts).toHaveLength(2); expect(plan.productPosts).toBe(1); expect(plan.informationalPosts).toBe(1); expect(plan.notes[0]).toMatch(/reduzido/i); expect(plan.suggestedPosts[0]?.timeReason).toMatch(/hipótese/i); });
  it("mantém link fora do body e comentário como ação manual", async () => { const repository = new MemoryRepository(); repository.values = [candidate("1")]; const post = (await new FacebookStrategyEngine(repository).createDailyPlan("w1", new Date(), 1)).suggestedPosts[0]!; expect(post.copy).not.toContain("https://"); expect(post.preparedComment?.affiliateUrl).toContain("https://"); expect(post.commentAction).toBe("MANUAL_REQUIRED"); });
  it("usa NONE sem affiliate URL e rejeita COMMENT inconsistente", async () => { const repository = new MemoryRepository(); repository.values = [candidate("none", { affiliateUrl: null, preparedComment: null })]; const plan = await new FacebookStrategyEngine(repository).createDailyPlan("w1", new Date(), 1); expect(plan.suggestedPosts[0]?.linkPlacement).toBe("NONE"); await expect(new FacebookStrategyEngine(repository).preparePost("w1", "none")).rejects.toThrow("affiliate_url_required"); });
  it("preserva BODY quando explicitamente configurado e não cria comentário", async () => { const repository = new MemoryRepository(); repository.values = [candidate("body", { linkPlacement: "BODY", preparedComment: null, copy: "Uma solução útil para a casa está em https://example.com/afiliado conforme configuração explícita." })]; const post = (await new FacebookStrategyEngine(repository).createDailyPlan("w1", new Date(), 1)).suggestedPosts[0]!; expect(post.linkPlacement).toBe("BODY"); expect(post.preparedComment).toBeNull(); expect(post.commentAction).toBeNull(); });
  it("avalia reuse, permite novo angle e previne duplicação", () => { const engine = new FacebookStrategyEngine(new MemoryRepository()), history = [candidate("1", { productId: "p1", contentAngle: "organization" })]; expect(engine.evaluateReuse(history, "p1", "organization").reuseAllowed).toBe(false); expect(engine.evaluateReuse(history, "p1", "practicality")).toMatchObject({ reuseAllowed: true }); });
  it("gera brief com imagem real, vídeo/reel e freshness compartilhada", () => { const engine = new FacebookStrategyEngine(new MemoryRepository(), undefined, { creativePriceFreshnessHours: 6 }); expect(engine.creativeBrief(candidate("1", { priceCheckedAt: new Date(Date.now() - 7 * 3_600_000) })).requiresPriceRefresh).toBe(true); expect(engine.creativeBrief(candidate("2", { contentPillar: "reel" })).visualStyle).toMatch(/vídeo/i); });
  it("exige capabilities e sempre prepara com approval", async () => { const repository = new MemoryRepository(); repository.values = [candidate("1")]; const engine = new FacebookStrategyEngine(repository); repository.capabilities.create_post = false; await expect(engine.preparePost("w1", "1")).rejects.toThrow("capability_unavailable:create_post"); repository.capabilities.create_post = true; await expect(engine.preparePost("w1", "1")).resolves.toMatchObject({ status: "approval_required", commentAction: "MANUAL_REQUIRED" }); expect(repository.prepared).toBe(1); });
  it("rejeita imagem ausente e link COMMENT no corpo", async () => { const repository = new MemoryRepository(), engine = new FacebookStrategyEngine(repository); repository.values = [candidate("image", { images: [] })]; await expect(engine.preparePost("w1", "image")).rejects.toThrow("product_image_required"); repository.values = [candidate("body", { copy: "Este texto suficientemente longo contém https://example.com indevidamente." })]; await expect(engine.preparePost("w1", "body")).rejects.toThrow("comment_link_must_not_be_in_body"); });
});
