import { dailyFacebookPlanSchema, facebookCreativeBriefSchema, facebookReuseEvaluationSchema, weeklyFacebookStrategySchema, type ContentAngle, type DailyFacebookPlan, type FacebookContentPillar, type FacebookCreativeBrief, type FacebookReuseEvaluation, type WeeklyFacebookStrategy } from "@casapratica/domain";
import { DEFAULT_CREATIVE_PRICE_CONFIG, isPriceFresh, type CreativePriceConfig } from "./creative-config.js";

export interface FacebookContentCandidate { contentId: string; variantId: string; productId: string | null; contentPillar: FacebookContentPillar; contentAngle: ContentAngle; copy: string; cta: string | null; linkPlacement: "COMMENT" | "BODY" | "NONE"; preparedComment: { body: string; affiliateUrl: string; affiliateDisclosure: string } | null; visualBrief: string; affiliateUrl: string | null; productName: string | null; category: string | null; images: readonly string[]; currentPrice: number | null; priceCheckedAt: Date | null; createdAt: Date }
export interface FacebookCapability { available: boolean; reason: string }
export interface FacebookStrategyRepository {
  saveStrategy(workspaceId: string, strategy: WeeklyFacebookStrategy): Promise<WeeklyFacebookStrategy>;
  getStrategy(workspaceId: string): Promise<WeeklyFacebookStrategy | null>;
  listFacebookContent(workspaceId: string): Promise<readonly FacebookContentCandidate[]>;
  getFacebookContent(workspaceId: string, contentOrProductId: string): Promise<FacebookContentCandidate | null>;
  createPublicationPreparation(workspaceId: string, content: FacebookContentCandidate, brief: FacebookCreativeBrief, commentAction: "MANUAL_REQUIRED" | null): Promise<{ queueItemId: string; status: "approval_required"; commentAction: "MANUAL_REQUIRED" | null }>;
  getCapability(workspaceId: string, capability: "read_page" | "create_post"): Promise<FacebookCapability>;
}
export interface FacebookPageProvider { listPages(): Promise<readonly { id: string; name: string }[]> }
export interface FacebookStrategyConfig extends CreativePriceConfig { initialDailyTarget: number; contentPillarDistribution: Partial<Record<FacebookContentPillar, number>> }
const defaultConfig: FacebookStrategyConfig = { ...DEFAULT_CREATIVE_PRICE_CONFIG, initialDailyTarget: 4, contentPillarDistribution: { product: 30, utility: 20, informational: 15, problem_solution: 10, organization: 10, engagement: 5, seasonal: 10 } };
const normalized = (value: string) => value.toLocaleLowerCase("pt-BR").replace(/\W/g, "");
const alternativeAngles: readonly ContentAngle[] = ["problem_solution", "organization", "space_saving", "practicality", "comparison", "seasonal", "utility"];

export class FacebookStrategyEngine {
  readonly config: FacebookStrategyConfig;
  constructor(private readonly repository: FacebookStrategyRepository, private readonly pageProvider?: FacebookPageProvider, config: Partial<FacebookStrategyConfig> = {}) { this.config = { ...defaultConfig, ...config, contentPillarDistribution: { ...defaultConfig.contentPillarDistribution, ...config.contentPillarDistribution } }; }
  async createWeeklyStrategy(workspaceId: string, start: Date, seasonalContext?: string | null): Promise<WeeklyFacebookStrategy> { const content = this.unique(await this.repository.listFacebookContent(workspaceId)); const daily = content.length ? Math.min(20, this.config.initialDailyTarget, Math.max(1, Math.ceil(content.length / 7))) : 0; const count = (pillars: readonly FacebookContentPillar[]) => content.filter(value => pillars.includes(value.contentPillar)).length; const strategy = weeklyFacebookStrategySchema.parse({ period: { start, end: new Date(start.getTime() + 6 * 86_400_000) }, goals: ["Construir confiança com conteúdo útil", "Apresentar produtos sem aparência de catálogo"], suggestedDailyVolume: daily, contentPillarDistribution: this.config.contentPillarDistribution, productContent: count(["product", "comparison"]), utilityContent: count(["utility", "tip", "organization", "problem_solution"]), informationalContent: count(["informational", "engagement", "video", "reel"]), seasonalContent: seasonalContext ? count(["seasonal"]) : 0, experiments: ["Testar aberturas conversacionais e problemas domésticos reais"], risks: content.length < this.config.initialDailyTarget * 7 ? ["Volume reduzido por falta de conteúdo distinto e qualificado."] : [], reasoning: "O mix é configurável e o volume inicial privilegia qualidade, diversidade e relacionamento em vez do teto diário.", confidence: content.length ? .78 : .4, futureMetrics: ["reach", "impressions", "engagement", "clicks", "reactions", "comments", "shares", "videoViews"] }); return this.repository.saveStrategy(workspaceId, strategy); }
  async createDailyPlan(workspaceId: string, date: Date, requestedPosts = this.config.initialDailyTarget): Promise<DailyFacebookPlan> { const limit = Math.min(20, requestedPosts); const content = this.unique(await this.repository.listFacebookContent(workspaceId)).slice(0, limit); const times = ["09:00", "13:00", "18:00", "20:00"]; const suggestedPosts = content.map((item, index) => ({ contentId: item.contentId, productId: item.productId, contentPillar: item.contentPillar, contentAngle: item.contentAngle, copy: item.copy, cta: item.cta, linkPlacement: item.productId && !item.affiliateUrl ? "NONE" as const : item.linkPlacement, preparedComment: item.productId && item.affiliateUrl && item.linkPlacement === "COMMENT" ? item.preparedComment : null, commentAction: item.productId && item.affiliateUrl && item.linkPlacement === "COMMENT" ? "MANUAL_REQUIRED" as const : null, visualBrief: item.visualBrief, creativeBrief: this.creativeBrief(item, date), status: "draft" as const, suggestedTime: times[index % times.length] ?? null, timeReason: "Horário inicial apenas como hipótese; ainda não há métricas reais de desempenho.", timeConfidence: .35 })); const productPosts = suggestedPosts.filter(value => value.productId).length; const utilityPosts = suggestedPosts.filter(value => !value.productId && ["utility", "tip", "organization", "problem_solution"].includes(value.contentPillar)).length; return dailyFacebookPlanSchema.parse({ date, suggestedPosts, productPosts, utilityPosts, informationalPosts: suggestedPosts.length - productPosts - utilityPosts, notes: content.length < requestedPosts ? ["Volume reduzido automaticamente por qualidade e diversidade disponíveis."] : [], approvalsRequired: true }); }
  evaluateReuse(history: readonly FacebookContentCandidate[], productId: string, proposedAngle?: ContentAngle): FacebookReuseEvaluation { const recent = history.filter(value => value.productId === productId); if (!recent.length) return facebookReuseEvaluationSchema.parse({ reuseAllowed: true, reason: "Produto ainda não aparece no histórico de conteúdo do Facebook.", recommendedAngle: proposedAngle ?? "problem_solution" }); const used = new Set(recent.map(value => value.contentAngle)); const recommendation = alternativeAngles.find(angle => !used.has(angle)) ?? null; const duplicate = proposedAngle ? used.has(proposedAngle) : false; return facebookReuseEvaluationSchema.parse({ reuseAllowed: Boolean(recommendation) && !duplicate, reason: duplicate ? "A abordagem proposta já foi usada recentemente; escolha uma razão editorial realmente diferente." : recommendation ? "O produto pode reaparecer com novo uso, problema ou abordagem editorial." : "As abordagens disponíveis estão saturadas no histórico recente.", recommendedAngle: recommendation }); }
  async evaluateStoredReuse(workspaceId: string, productId: string, proposedAngle?: ContentAngle) { return this.evaluateReuse(await this.repository.listFacebookContent(workspaceId), productId, proposedAngle); }
  creativeBrief(content: FacebookContentCandidate, now = new Date()): FacebookCreativeBrief { const fresh = isPriceFresh(content.currentPrice, content.priceCheckedAt, now, this.config); return facebookCreativeBriefSchema.parse({ preferredProductImage: content.images[0] ?? null, imageSelectionReason: content.images[0] ? "Imagem real disponível no anúncio; seleção avançada fica para a Fase 9." : "Nenhuma imagem real disponível; não recriar o produto com IA.", headline: content.productName ?? content.copy.slice(0, 60), productFacts: [content.productName, content.category].filter((value): value is string => Boolean(value)).slice(0, 2), priceDisplayRequested: fresh, requiresPriceRefresh: content.currentPrice !== null && !fresh, brandPlacement: "CasaPrática pequena e discreta no canto", visualStyle: content.contentPillar === "video" || content.contentPillar === "reel" ? "Brief de vídeo vertical; produção futura" : "Visual limpo e conversacional", notes: ["Usar imagem real", "Até duas informações verificadas", "Não inserir CTA grande no criativo"] }); }
  prepareComment(content: FacebookContentCandidate) { if (content.linkPlacement !== "COMMENT") return { preparedComment: null, commentAction: null }; if (!content.affiliateUrl || !content.preparedComment) throw new Error("affiliate_comment_required"); return { preparedComment: content.preparedComment, commentAction: "MANUAL_REQUIRED" as const }; }
  async prepareStoredComment(workspaceId: string, contentId: string) { const content = await this.repository.getFacebookContent(workspaceId, contentId); if (!content) throw new Error("facebook_content_not_found"); return this.prepareComment(content); }
  async preparePost(workspaceId: string, contentId: string) { const content = await this.repository.getFacebookContent(workspaceId, contentId); if (!content) throw new Error("facebook_content_not_found"); if (content.productId && content.linkPlacement === "COMMENT" && !content.affiliateUrl) throw new Error("affiliate_url_required"); if (content.linkPlacement === "COMMENT" && /https?:\/\//i.test(content.copy)) throw new Error("comment_link_must_not_be_in_body"); const brief = this.creativeBrief(content); if (content.productId && !brief.preferredProductImage) throw new Error("product_image_required"); if (brief.requiresPriceRefresh) throw new Error("price_refresh_required"); for (const capability of ["read_page", "create_post"] as const) { const result = await this.repository.getCapability(workspaceId, capability); if (!result.available) throw new Error(`capability_unavailable:${capability}:${result.reason}`); } const comment = this.prepareComment(content); return this.repository.createPublicationPreparation(workspaceId, content, brief, comment.commentAction); }
  async listPages(workspaceId: string) { const capability = await this.repository.getCapability(workspaceId, "read_page"); if (!capability.available) throw new Error(`capability_unavailable:read_page:${capability.reason}`); if (!this.pageProvider) throw new Error("facebook_provider_not_configured"); return this.pageProvider.listPages(); }
  getStrategy(workspaceId: string) { return this.repository.getStrategy(workspaceId); }
  getContentHistory(workspaceId: string) { return this.repository.listFacebookContent(workspaceId); }
  private unique(values: readonly FacebookContentCandidate[]) { const keys = new Set<string>(); return values.filter(value => { const key = `${normalized(value.copy)}:${value.contentAngle}:${value.contentPillar}`; if (keys.has(key)) return false; keys.add(key); return true; }); }
}
