import { describe, expect, it } from "vitest";
import { PinterestStrategyEngine, generatePinterestKeywordCluster, inferPinterestIntent, recommendPinterestBoard, type PinterestContentCandidate, type PinterestStrategyRepository } from "./pinterest-strategy.js";

const candidate = (id: string, changes: Partial<PinterestContentCandidate> = {}): PinterestContentCandidate => ({ contentId: id, variantId: `v-${id}`, productId: `p-${id}`, title: `Organizador ${id}`, description: "Uma ideia de organização para cozinha pequena.", cta: "Confira os detalhes.", keywords: ["organização da cozinha", "cozinha pequena"], keywordCluster: `cluster-${id}`, contentAngle: "organization", visualBrief: "Usar imagem real do produto.", boardSuggestion: "Cozinha Prática", affiliateUrl: "https://example.com/afiliado", productName: "Organizador", category: "Cozinha", images: ["https://example.com/image.jpg"], currentPrice: 89, priceCheckedAt: new Date(), createdAt: new Date(), ...changes });
class MemoryPinterestRepository implements PinterestStrategyRepository { values: PinterestContentCandidate[] = []; capability = true; strategy = null as Awaited<ReturnType<PinterestStrategyRepository["getStrategy"]>>; prepared = 0; async saveStrategy(_workspaceId: string, strategy: NonNullable<typeof this.strategy>) { this.strategy = strategy; return strategy; } async getStrategy() { return this.strategy; } async listPinterestContent() { return this.values; } async getPinterestContent(_workspaceId: string, id: string) { return this.values.find(value => value.contentId === id) ?? null; } async createPublicationPreparation() { this.prepared++; return { queueItemId: "q1", status: "approval_required" as const }; } async getCapability() { return { available: this.capability, reason: this.capability ? "available" : "scope_missing" }; } }
describe("PinterestStrategyEngine", () => {
  it("recomenda board por evidência, não aleatoriamente", () => expect(recommendPinterestBoard({ category: "Cozinha", keywords: ["panela"] })).toMatchObject({ boardSuggestion: "Cozinha Prática", confidence: .95 }));
  it("gera keyword cluster e search intent", () => { const cluster = generatePinterestKeywordCluster("carrinho para cozinha pequena"); expect(cluster.keywords.length).toBeGreaterThanOrEqual(2); expect(inferPinterestIntent("ideias para banheiro")).toBe("bathroom"); });
  it("limita a 10 Pins e reduz volume quando faltam opções distintas", async () => { const repository = new MemoryPinterestRepository(); repository.values = [candidate("1"), candidate("2"), candidate("3")]; const engine = new PinterestStrategyEngine(repository); const plan = await engine.createDailyPlan("w1", new Date(), 10); expect(plan.suggestedPins).toHaveLength(3); expect(plan.notes[0]).toMatch(/reduzido/i); repository.values = Array.from({ length: 12 }, (_, index) => candidate(String(index))); expect((await engine.createDailyPlan("w1", new Date(), 10)).suggestedPins).toHaveLength(10); });
  it("remove duplicação e permite reutilização com novo angle/cluster", async () => { const repository = new MemoryPinterestRepository(); repository.values = [candidate("1"), candidate("2", { title: "Organizador 1", keywordCluster: "cluster-1" }), candidate("3", { title: "Organizador 1", contentAngle: "practicality" })]; const plan = await new PinterestStrategyEngine(repository).createDailyPlan("w1", new Date()); expect(plan.suggestedPins.map(pin => pin.contentId)).toEqual(["1", "3"]); });
  it("mantém conteúdo útil e sazonal no plano semanal", async () => { const repository = new MemoryPinterestRepository(); repository.values = [candidate("1"), candidate("u", { productId: null, affiliateUrl: null })]; const strategy = await new PinterestStrategyEngine(repository).createWeeklyStrategy("w1", new Date(), "Natal"); expect(strategy.utilityContent).toBe(1); expect(strategy.seasonalContent).toBeGreaterThan(0); expect(strategy.suggestedDailyVolume).toBeLessThanOrEqual(10); });
  it("controla freshness de preço por configuração", () => { const engine = new PinterestStrategyEngine(new MemoryPinterestRepository(), undefined, { creativePriceFreshnessHours: 6 }); expect(engine.creativeBrief(candidate("1", { priceCheckedAt: new Date(Date.now() - 7 * 3_600_000) })).requiresPriceRefresh).toBe(true); expect(engine.creativeBrief(candidate("1")).priceDisplayRequested).toBe(true); });
  it("bloqueia produto sem imagem, sem afiliado e capability indisponível", async () => { const repository = new MemoryPinterestRepository(), engine = new PinterestStrategyEngine(repository); repository.values = [candidate("no-link", { affiliateUrl: null })]; await expect(engine.preparePin("w1", "no-link")).rejects.toThrow("affiliate_url_required"); repository.values = [candidate("no-image", { images: [] })]; await expect(engine.preparePin("w1", "no-image")).rejects.toThrow("product_image_required"); repository.values = [candidate("ok")]; repository.capability = false; await expect(engine.preparePin("w1", "ok")).rejects.toThrow("capability_unavailable"); });
  it("prepara com approval obrigatório sem publicar", async () => { const repository = new MemoryPinterestRepository(); repository.values = [candidate("ok")]; const result = await new PinterestStrategyEngine(repository).preparePin("w1", "ok"); expect(result.status).toBe("approval_required"); expect(repository.prepared).toBe(1); });
});
