import { dailyPinterestPlanSchema, pinterestBoardRecommendationSchema, pinterestCreativeBriefSchema, pinterestKeywordClusterSchema, weeklyPinterestStrategySchema, type ContentAngle, type DailyPinterestPlan, type PinterestCreativeBrief, type PinterestKeywordCluster, type PinterestSearchIntent, type WeeklyPinterestStrategy } from "@casapratica/domain";
import { DEFAULT_CREATIVE_PRICE_CONFIG, isPriceFresh, type CreativePriceConfig } from "./creative-config.js";

export const DEFAULT_PINTEREST_BOARDS = ["Organização da Casa", "Cozinha Prática", "Casa Pequena", "Banheiro Organizado", "Lavanderia e Limpeza", "Quarto Organizado", "Sala e Decoração", "Utilidades para Casa"] as const;
export interface PinterestContentCandidate { contentId: string; variantId: string; productId: string | null; title: string; description: string; cta: string; keywords: readonly string[]; keywordCluster: string; contentAngle: ContentAngle; visualBrief: string; boardSuggestion: string; affiliateUrl: string | null; productName: string | null; category: string | null; images: readonly string[]; currentPrice: number | null; priceCheckedAt: Date | null; createdAt: Date }
export interface PinterestCapability { available: boolean; reason: string }
export interface PinterestStrategyRepository {
  saveStrategy(workspaceId: string, strategy: WeeklyPinterestStrategy): Promise<WeeklyPinterestStrategy>;
  getStrategy(workspaceId: string): Promise<WeeklyPinterestStrategy | null>;
  listPinterestContent(workspaceId: string): Promise<readonly PinterestContentCandidate[]>;
  getPinterestContent(workspaceId: string, contentId: string): Promise<PinterestContentCandidate | null>;
  createPublicationPreparation(workspaceId: string, content: PinterestContentCandidate, board: string, brief: PinterestCreativeBrief): Promise<{ queueItemId: string; status: "approval_required" }>;
  getCapability(workspaceId: string, capability: "read_boards" | "create_pin"): Promise<PinterestCapability>;
}
export interface PinterestBoardProvider { listBoards(): Promise<readonly { id: string; name: string }[]> }
export type PinterestStrategyConfig = CreativePriceConfig;
const lower = (value: string) => value.toLocaleLowerCase("pt-BR");

export function inferPinterestIntent(text: string): PinterestSearchIntent { const value = lower(text); if (/cozinha/.test(value)) return "kitchen"; if (/banheiro/.test(value)) return "bathroom"; if (/lavanderia/.test(value)) return "laundry"; if (/pequen|espaço/.test(value)) return "small_space"; if (/limp/.test(value)) return "cleaning"; if (/decor/.test(value)) return "decoration"; if (/sazon|natal|black friday|verão|inverno|mães|aulas/.test(value)) return "seasonal"; if (/problema|solução/.test(value)) return "problem_solution"; if (/produto|compr|opção/.test(value)) return "product_discovery"; if (/prátic/.test(value)) return "practicality"; return "organization"; }
export function generatePinterestKeywordCluster(topic: string): PinterestKeywordCluster { const intent = inferPinterestIntent(topic), clean = topic.trim(); return pinterestKeywordClusterSchema.parse({ name: clean, intent, keywords: [{ value: clean, intent, relation: "product" }, { value: `${clean} para casa`, intent, relation: "category" }, { value: intent === "small_space" ? "economia de espaço" : "organização da casa", intent, relation: intent === "small_space" ? "benefit" : "problem" }] }); }
export function recommendPinterestBoard(input: { category?: string | null; keywords?: readonly string[]; intent?: PinterestSearchIntent; content?: string }): { boardSuggestion: string; reason: string; confidence: number } { const text = lower([input.category, ...(input.keywords ?? []), input.intent, input.content].filter(Boolean).join(" ")); const rules: readonly [RegExp, string, number][] = [[/cozinha/, "Cozinha Prática", .95], [/banheiro/, "Banheiro Organizado", .95], [/lavanderia|limpeza/, "Lavanderia e Limpeza", .9], [/quarto/, "Quarto Organizado", .9], [/sala|decoração/, "Sala e Decoração", .9], [/pequen|small_space|espaço/, "Casa Pequena", .88], [/organiz/, "Organização da Casa", .85]]; const match = rules.find(([pattern]) => pattern.test(text)); const boardSuggestion = match?.[1] ?? "Utilidades para Casa", confidence = match?.[2] ?? .65; return pinterestBoardRecommendationSchema.parse({ boardSuggestion, confidence, reason: `Recomendação baseada em categoria, keywords e intenção detectadas; board estratégico não é criado automaticamente.` }); }

export class PinterestStrategyEngine {
  readonly config: PinterestStrategyConfig;
  constructor(private readonly repository: PinterestStrategyRepository, private readonly boardProvider?: PinterestBoardProvider, config: Partial<PinterestStrategyConfig> = {}) { this.config = { ...DEFAULT_CREATIVE_PRICE_CONFIG, ...config }; }
  async createWeeklyStrategy(workspaceId: string, start: Date, seasonalContext?: string | null): Promise<WeeklyPinterestStrategy> { const content = await this.repository.listPinterestContent(workspaceId), usable = this.unique(content), daily = Math.min(10, Math.max(1, Math.ceil(usable.length / 7))), productContent = usable.filter(value => value.productId).length, utilityContent = usable.length - productContent, clusterTopics = [...new Set(usable.flatMap(value => value.keywords).slice(0, 6))]; const strategy = weeklyPinterestStrategySchema.parse({ period: { start, end: new Date(start.getTime() + 6 * 86_400_000) }, goals: ["Equilibrar descoberta de produtos e conteúdo útil", "Evitar repetição excessiva"], suggestedDailyVolume: usable.length ? daily : 0, boardDistribution: Object.fromEntries(DEFAULT_PINTEREST_BOARDS.map(board => [board, board === "Organização da Casa" ? 25 : 75 / 7])), keywordClusters: clusterTopics.map(generatePinterestKeywordCluster), productContent, utilityContent, seasonalContent: seasonalContext ? Math.min(2, usable.length) : 0, experiments: ["Testar abordagens de organização e praticidade"], risks: usable.length < 7 ? ["Pouco conteúdo distinto disponível; volume reduzido automaticamente."] : [], reasoning: "Volume limitado pela qualidade e diversidade disponível, mantendo conteúdo útil para evitar catálogo de links.", confidence: usable.length ? .8 : .4, futureMetrics: ["impressions", "saves", "pinClicks", "outboundClicks", "engagement"] }); return this.repository.saveStrategy(workspaceId, strategy); }
  getStrategy(workspaceId: string) { return this.repository.getStrategy(workspaceId); }
  generateKeywords(topic: string) { return generatePinterestKeywordCluster(topic); }
  recommendBoard(input: Parameters<typeof recommendPinterestBoard>[0]) { return recommendPinterestBoard(input); }
  async createDailyPlan(workspaceId: string, date: Date, requestedPins = 10): Promise<DailyPinterestPlan> { const content = this.unique(await this.repository.listPinterestContent(workspaceId)).slice(0, Math.min(10, requestedPins)); const suggestedPins = content.map(item => { const board = recommendPinterestBoard({ category: item.category, keywords: item.keywords, content: item.description }); return { contentId: item.contentId, productId: item.productId, title: item.title, description: item.description, cta: item.cta, boardSuggestion: board.boardSuggestion, keywordCluster: item.keywordCluster, contentAngle: item.contentAngle, visualBrief: item.visualBrief, affiliateUrl: item.affiliateUrl, status: "draft" as const, creativeBrief: this.creativeBrief(item, date) }; }); const productPins = suggestedPins.filter(value => value.productId).length; return dailyPinterestPlanSchema.parse({ date, suggestedPins, productPins, utilityPins: suggestedPins.length - productPins, boardDistribution: suggestedPins.reduce<Record<string, number>>((result, pin) => ({ ...result, [pin.boardSuggestion]: (result[pin.boardSuggestion] ?? 0) + 1 }), {}), notes: suggestedPins.length < requestedPins ? ["Volume reduzido: não há conteúdo distinto e qualificado suficiente."] : [], approvalsRequired: true }); }
  creativeBrief(content: PinterestContentCandidate, now = new Date()): PinterestCreativeBrief { const fresh = isPriceFresh(content.currentPrice, content.priceCheckedAt, now, this.config); return pinterestCreativeBriefSchema.parse({ preferredProductImage: content.images[0] ?? null, imageSelectionReason: content.images[0] ? "Primeira imagem real disponível no anúncio; seleção visual avançada fica para a Fase 9." : "Nenhuma imagem real disponível; não recriar o produto com IA.", headline: content.title, productFacts: [content.productName, content.category].filter((value): value is string => Boolean(value)).slice(0, 2), priceDisplayRequested: fresh, requiresPriceRefresh: content.currentPrice !== null && !fresh, brandPlacement: "CasaPrática pequena e discreta no canto", notes: ["Usar imagem real do produto", "Limitar texto visual ao nome curto e até duas informações"] }); }
  async preparePin(workspaceId: string, contentId: string) { const content = await this.repository.getPinterestContent(workspaceId, contentId); if (!content) throw new Error("pinterest_content_not_found"); if (content.productId && !content.affiliateUrl) throw new Error("affiliate_url_required"); const brief = this.creativeBrief(content); if (content.productId && !brief.preferredProductImage) throw new Error("product_image_required"); if (brief.requiresPriceRefresh) throw new Error("price_refresh_required"); const capability = await this.repository.getCapability(workspaceId, "create_pin"); if (!capability.available) throw new Error(`capability_unavailable:create_pin:${capability.reason}`); const board = recommendPinterestBoard({ category: content.category, keywords: content.keywords, content: content.description }); return this.repository.createPublicationPreparation(workspaceId, content, board.boardSuggestion, brief); }
  async listBoards(workspaceId: string) { const capability = await this.repository.getCapability(workspaceId, "read_boards"); if (!capability.available) throw new Error(`capability_unavailable:read_boards:${capability.reason}`); if (!this.boardProvider) throw new Error("pinterest_provider_not_configured"); return this.boardProvider.listBoards(); }
  getContentHistory(workspaceId: string) { return this.repository.listPinterestContent(workspaceId); }
  private unique(values: readonly PinterestContentCandidate[]) { const keys = new Set<string>(); return values.filter(value => { const key = `${lower(value.title).replace(/\W/g, "")}:${value.contentAngle}:${value.keywordCluster}`; if (keys.has(key)) return false; keys.add(key); return true; }); }
}
