import { describe, expect, it } from "vitest";
import type { MarketplaceProductProvider } from "@casapratica/integrations";
import { ProductResearchService, scoreCandidate, type ResearchRepository, type SavedResearchRun } from "./research.js";
import { completeFixture, sparseFixture } from "./fixtures.js";
class MemoryRepository implements ResearchRepository { runs: SavedResearchRun[] = []; async save(run: Omit<SavedResearchRun,"id">) { const value = { ...run, id: "run-1" }; this.runs.push(value); return value; } async list() { return this.runs; } async getCandidate(_workspaceId: string, externalId: string) { return this.runs.flatMap(run=>run.candidates).find(value=>value.product.externalId===externalId) ?? null; } async setProductStatus() {} }
const provider = (values: readonly typeof completeFixture[]): MarketplaceProductProvider => ({ marketplace: "mercadolivre", searchProducts: async () => values, getProduct: async id => values.find(value=>value.externalId===id) ?? null, getSeller: async () => null, getCategories: async () => [], refreshProductData: async id => values.find(value=>value.externalId===id) ?? null });
describe("product research", () => {
  it("mantém ausência distinta de zero no score", () => { const score = scoreCandidate(sparseFixture, [sparseFixture]); expect(score.missingFactors).toContain("demand"); expect(score.factorScores.demand).toBeUndefined(); });
  it("deduplica, não completa a meta e registra o motivo", async () => { const repository = new MemoryRepository(); const service = new ProductResearchService(provider([completeFixture, completeFixture, sparseFixture]), repository); const run = await service.research({ workspaceId: "workspace", queries: ["organização"], targetCandidates: 20 }); expect(run.candidates).toHaveLength(2); expect(run.candidates[0]?.product.externalId).toBe("MLB1"); expect(run.reasons.MLB1?.length).toBeGreaterThan(0); expect(run.approved + run.tests + run.rejected).toBe(2); });
  it("recusa comparação entre categorias diferentes", async () => { const other = { ...completeFixture, externalId: "MLB3", canonicalUrl: "https://produto.mercadolivre.com.br/MLB3", categoryExternalId: "OTHER" }; const repository = new MemoryRepository(); const service = new ProductResearchService(provider([completeFixture, other]), repository); await service.research({ workspaceId: "workspace", queries: ["casa"] }); await expect(service.compare("workspace", ["MLB1", "MLB3"])).rejects.toThrow("products_not_comparable"); });
});
