import { describe, expect, it, vi } from "vitest";
import type { MarketplaceProductProvider } from "@casapratica/integrations";
import { ProductResearchService, allocateCategoryTargets, generateWinnerQueries, scoreCandidate, verdictFor, zoeVerdictFor, type ResearchRepository, type SavedResearchRun } from "./research.js";
import { completeFixture, sparseFixture } from "./fixtures.js";

class MemoryRepository implements ResearchRepository { runs: SavedResearchRun[] = []; async save(run: Omit<SavedResearchRun, "id">) { const value = { ...run, id: "run-1" }; this.runs.push(value); return value; } async list() { return this.runs; } async getCandidate(_workspaceId: string, externalId: string) { return this.runs.flatMap(run => run.candidates).find(value => value.product.externalId === externalId) ?? null; } async setProductStatus() {} }
const provider = (values: readonly typeof completeFixture[]): MarketplaceProductProvider => ({ marketplace: "mercadolivre", searchProducts: async () => values, getProduct: async id => values.find(value => value.externalId === id) ?? null, getSeller: async () => null, getCategories: async () => [], refreshProductData: async id => values.find(value => value.externalId === id) ?? null });
const variant = (id: string, price: number, changes = {}) => ({ ...completeFixture, externalId: id, canonicalUrl: `https://produto.mercadolivre.com.br/${id}`, price, ...changes });

describe("product research", () => {
  it("mantém ausência distinta de zero no score", () => { const score = scoreCandidate(sparseFixture, [sparseFixture]); expect(score.missingFactors).toContain("demand"); expect(score.factorScores.demand).toBeUndefined(); });
  it("deduplica, não completa a meta com produtos ruins e persiste o run", async () => { const repository = new MemoryRepository(), service = new ProductResearchService(provider([completeFixture, completeFixture, sparseFixture]), repository); const run = await service.research({ workspaceId: "workspace", queries: ["organização"], targetCandidates: 20 }); expect(run.candidates).toHaveLength(2); expect(run.reasons.MLB1?.length).toBeGreaterThan(0); expect(run.recommended + run.opportunities + run.rejected).toBe(2); expect(repository.runs).toHaveLength(1); });
  it("exige três anúncios equivalentes e prioriza o mais barato quando a qualidade é comparável", async () => { const values = [variant("MLB1", 89), variant("MLB2", 69), variant("MLB3", 79)], repository = new MemoryRepository(), service = new ProductResearchService(provider(values), repository); await service.research({ workspaceId: "workspace", queries: ["organizador"] }); await expect(service.compare("workspace", ["MLB1", "MLB2"])).rejects.toThrow("minimum_three"); const result = await service.compare("workspace", values.map(value => value.externalId)); expect(result.winner?.product.externalId).toBe("MLB2"); });
  it("recusa comparação de produtos não equivalentes", async () => { const values = [variant("MLB1", 89), variant("MLB2", 69), variant("MLB3", 79, { name: "Panela elétrica", categoryExternalId: "OTHER" })], repository = new MemoryRepository(), service = new ProductResearchService(provider(values), repository); await service.research({ workspaceId: "workspace", queries: ["casa"] }); await expect(service.compare("workspace", values.map(value => value.externalId))).rejects.toThrow("products_not_comparable"); });
  it("aceita rating 4.6 de forma contextual e não torna preço fora da faixa uma rejeição automática", () => { const product = variant("MLB4", 25, { rating: 4.6, reviewCount: 200 }); expect(verdictFor(product, scoreCandidate(product, [product]), [product])).not.toBe("NÃO RECOMENDADO"); const premium = variant("MLB5", 650); expect(verdictFor(premium, scoreCandidate(premium, [premium]), [premium])).not.toBe("NÃO RECOMENDADO"); });
  it("classifica produto novo confiável como oportunidade e rejeita quando confiança essencial falta", () => { const fresh = variant("MLB6", 90, { salesCount: 2, reviewCount: 2 }); expect(verdictFor(fresh, scoreCandidate(fresh, [fresh]), [fresh])).toBe("OPORTUNIDADE PARA REVISÃO"); expect(verdictFor(sparseFixture, scoreCandidate(sparseFixture, [sparseFixture]), [sparseFixture])).toBe("NÃO RECOMENDADO"); });
  it("mantém diversidade no peso de categorias", () => { const allocation = allocateCategoryTargets(["Organização", "Cozinha", "Outras"], { Organização: 35, Cozinha: 25, Outras: 40 }, 20); expect(allocation.Organização).toBeGreaterThan(0); expect(allocation.Cozinha).toBeGreaterThan(0); expect(Object.values(allocation).reduce((a, b) => a + b, 0)).toBe(20); });
  it("carrega highlights por bulk e enriquece vendedores por bulk", async () => { const highlighted=variant("MLB-HIGHLIGHT",79,{sellerExternalId:"42",sellerName:null,sellerReputation:null}),getProducts=vi.fn().mockResolvedValue([highlighted]),getSellers=vi.fn().mockResolvedValue([{externalId:"42",name:"Loja Oficial",reputation:100,rawSourceReference:"mercadolivre:user:42"}]),base=provider([]),repository=new MemoryRepository(),service=new ProductResearchService({...base,getProducts,getSellers},repository);const run=await service.research({workspaceId:"workspace",queries:["organizador"],seedExternalIds:["MLB-HIGHLIGHT"]});expect(getProducts).toHaveBeenCalledWith(["MLB-HIGHLIGHT"]);expect(getSellers).toHaveBeenCalledWith(["42"]);expect(run.candidates[0]?.product).toMatchObject({externalId:"MLB-HIGHLIGHT",sellerName:"Loja Oficial",sellerReputation:100})});
  it("busca similares apenas para vencedores com venda, sem confundir clique", () => { expect(generateWinnerQueries([{ name: "Cesto", conversions: 0, clicks: 500 }, { name: "Panela", conversions: 2 }])).toEqual(["produtos similares a Panela"]); });
  describe("veredito ZOE_WEB_RESEARCH", () => {
    const fixedScore = (score: number, confidence: number) => ({ score, confidence, factorScores: {}, availableFactors: [], missingFactors: [], explanation: "fixture" });
    const partial = () => variant("ZOE1", 79, { sellerName: "Loja", sellerReputation: null, salesCount: null, reviewCount: 120, missingFields: ["salesCount", "sellerReputation"] });
    it("caso A: aprova score 88, confidence 65% e dados parciais", () => { const product = partial(); expect(zoeVerdictFor(product, fixedScore(88, .65), [product])).toBe("APROVADO PARA REVISÃO"); });
    it("caso B: trata score 79, confidence 40% e dados parciais como oportunidade", () => { const product = partial(); expect(zoeVerdictFor(product, fixedScore(79, .4), [product])).toBe("OPORTUNIDADE PARA REVISÃO"); });
    it("caso C: rejeita score 55 e confidence 30%", () => { const product = partial(); expect(zoeVerdictFor(product, fixedScore(55, .3), [product])).toBe("NÃO RECOMENDADO"); });
    it("caso D: risco crítico prevalece sobre score alto", () => { const product = variant("ZOE-RISK", 79, { canonicalUrl: "https://localhost/product" }); expect(zoeVerdictFor(product, fixedScore(95, .9), [product])).toBe("NÃO RECOMENDADO"); });
  });
});
