import { calculateCasaPraticaScore, type ProductStatus, type ScoreInput, type ScoreResult } from "@casapratica/domain";
import type { MarketplaceProduct, MarketplaceProductProvider } from "@casapratica/integrations";
export type Verdict = "APROVADO" | "TESTE" | "NÃO RECOMENDADO";
export interface RankedCandidate { product: MarketplaceProduct; score: ScoreResult; verdict: Verdict; reasons: readonly string[]; comparisonGroup: string }
export interface SavedResearchRun { id: string; workspaceId: string; date: Date; queries: readonly string[]; categories: readonly string[]; candidates: readonly RankedCandidate[]; approved: number; tests: number; rejected: number; reasons: Readonly<Record<string, readonly string[]>>; durationMs: number; provider: string }
export interface ResearchRepository { save(run: Omit<SavedResearchRun, "id">): Promise<SavedResearchRun>; list(workspaceId: string): Promise<readonly SavedResearchRun[]>; getCandidate(workspaceId: string, externalId: string): Promise<RankedCandidate | null>; setProductStatus(workspaceId: string, externalId: string, status: ProductStatus, reason: string): Promise<void> }
export interface ResearchRequest { workspaceId: string; queries: readonly string[]; categories?: readonly string[]; targetCandidates?: number }
const unique = (products: readonly MarketplaceProduct[]) => [...new Map(products.map(product => [`${product.externalId}:${product.canonicalUrl}`, product])).values()];
const eligible = (product: MarketplaceProduct) => product.externalId.length > 0 && product.name.length > 0 && product.canonicalUrl.length > 0 && product.availability !== "unavailable";
const scaledCount = (value: number | null, target: number) => value === null ? undefined : Math.min(100, value / target * 100);
export function scoreCandidate(product: MarketplaceProduct, group: readonly MarketplaceProduct[]): ScoreResult {
  const priced = group.map(item => item.price).filter((value): value is number => value !== null); const median = priced.length ? [...priced].sort((a,b)=>a-b)[Math.floor(priced.length / 2)] ?? null : null;
  const factors: ScoreInput = { demand: scaledCount(product.salesCount, 100), reviews: product.rating === null ? undefined : product.rating / 5 * 70 + Math.min(30, (product.reviewCount ?? 0) / 100 * 30), sellerReputation: product.sellerReputation ?? undefined, priceCompetitiveness: product.price === null || median === null || median === 0 ? undefined : Math.max(0, Math.min(100, 100 - Math.abs(product.price - median) / median * 100)), listingQuality: product.images.length === 0 ? undefined : Math.min(100, product.images.length * 20), commission: product.commission === null ? undefined : Math.min(100, product.commission), seasonality: undefined };
  return calculateCasaPraticaScore(factors);
}
const verdictFor = (score: ScoreResult): Verdict => score.score !== null && score.score >= 75 && score.confidence >= .55 ? "APROVADO" : score.score !== null && score.score >= 55 && score.confidence >= .35 ? "TESTE" : "NÃO RECOMENDADO";
export class ProductResearchService {
  constructor(private readonly provider: MarketplaceProductProvider, private readonly repository: ResearchRepository) {}
  async research(request: ResearchRequest) { const started = performance.now(), target = Math.min(request.targetCandidates ?? 20, 20), queries = generateQueries(request.queries, request.categories ?? []), perQuery = Math.max(1, Math.ceil(target / queries.length)); const batches = await Promise.all(queries.map(query => this.provider.searchProducts({ query, limit: perQuery }))); const normalized = unique(batches.flat()).filter(eligible).slice(0, target); const groups = normalized.reduce<Map<string, MarketplaceProduct[]>>((map, product) => { const key = product.categoryExternalId ?? `unknown:${product.externalId}`; map.set(key, [...(map.get(key) ?? []), product]); return map; }, new Map()); const candidates = normalized.map(product => { const score = scoreCandidate(product, groups.get(product.categoryExternalId ?? `unknown:${product.externalId}`) ?? [product]); const verdict = verdictFor(score); const reasons = [score.explanation, product.price !== null && (product.price < 30 || product.price > 500) ? "Preço fora da faixa preferencial de R$30 a R$500." : "Preço dentro da faixa preferencial ou ausente.", product.missingFields.length ? `Dados ausentes: ${product.missingFields.join(", ")}.` : "Campos essenciais disponíveis."]; return { product, score, verdict, reasons, comparisonGroup: product.categoryExternalId ?? `unknown:${product.externalId}` }; }).sort((a,b) => (b.score.score ?? -1) - (a.score.score ?? -1) || (b.score.factorScores.listingQuality ?? -1) - (a.score.factorScores.listingQuality ?? -1)); const counts = { approved: candidates.filter(value => value.verdict === "APROVADO").length, tests: candidates.filter(value => value.verdict === "TESTE").length, rejected: candidates.filter(value => value.verdict === "NÃO RECOMENDADO").length }; return this.repository.save({ workspaceId: request.workspaceId, date: new Date(), queries, categories: request.categories ?? [], candidates, ...counts, reasons: Object.fromEntries(candidates.map(value => [value.product.externalId, value.reasons])), durationMs: Math.round(performance.now() - started), provider: this.provider.marketplace }); }
  getProductDetails(externalId: string) { return this.provider.getProduct(externalId); }
  async compare(workspaceId: string, externalIds: readonly string[]) { const candidates = (await Promise.all(externalIds.map(id => this.repository.getCandidate(workspaceId, id)))).filter((value): value is RankedCandidate => value !== null); if (new Set(candidates.map(value => value.comparisonGroup)).size > 1) throw new Error("products_not_comparable"); const ranked = [...candidates].sort((a,b)=>(b.score.score ?? -1)-(a.score.score ?? -1)); return { considered: ranked.map(value => value.product.externalId), winner: ranked[0] ?? null, reason: ranked[0] ? `Maior score CasaPrática entre ${ranked.length} produto(s) comparáveis; fatores ausentes continuam explícitos.` : "Nenhum candidato comparável encontrado." }; }
  calculate(product: MarketplaceProduct, group: readonly MarketplaceProduct[] = [product]) { return scoreCandidate(product, group); }
  async calculateStored(workspaceId: string, externalId: string) { const candidate = await this.repository.getCandidate(workspaceId, externalId); if (!candidate) throw new Error("product_candidate_not_found"); return candidate.score; }
  listRuns(workspaceId: string) { return this.repository.list(workspaceId); }
  approve(workspaceId: string, externalId: string, reason: string) { return this.repository.setProductStatus(workspaceId, externalId, "approved", reason); }
  reject(workspaceId: string, externalId: string, reason: string) { return this.repository.setProductStatus(workspaceId, externalId, "rejected", reason); }
}
export function generateQueries(queries: readonly string[], categories: readonly string[]): readonly string[] { const clean = queries.map(value => value.trim()).filter(Boolean); if (clean.length > 0) return [...new Set(clean)]; const generated = categories.map(category => `melhores produtos para ${category}`).filter(Boolean); return generated.length > 0 ? generated : ["produtos úteis para casa"]; }
