import { describe, expect, it } from "vitest";
import type { MarketplaceProductProvider } from "@casapratica/integrations";
import { ProductResearchService, allocateCategoryTargets, generateWinnerQueries, scoreCandidate, verdictFor, type ResearchRepository, type SavedResearchRun } from "./research.js";
import { completeFixture, sparseFixture } from "./fixtures.js";

class MemoryRepository implements ResearchRepository { runs: SavedResearchRun[] = []; async save(run: Omit<SavedResearchRun, "id">) { const value = { ...run, id: "run-1" }; this.runs.push(value); return value; } async list() { return this.runs; } async getCandidate(_workspaceId: string, externalId: string) { return this.runs.flatMap(run => run.candidates).find(value => value.product.externalId === externalId) ?? null; } async setProductStatus() {} }
const provider = (values: readonly typeof completeFixture[]): MarketplaceProductProvider => ({ marketplace: "mercadolivre", searchProducts: async () => values, getProduct: async id => values.find(value => value.externalId === id) ?? null, getSeller: async () => null, getCategories: async () => [], refreshProductData: async id => values.find(value => value.externalId === id) ?? null });
const variant = (id: string, price: number, changes = {}) => ({ ...completeFixture, externalId: id, canonicalUrl: `https://produto.mercadolivre.com.br/${id}`, price, ...changes });

describe("product research", () => {
  it("mantém ausência distinta de zero no score", () => { const score = scoreCandidate(sparseFixture, [sparseFixture]); expect(score.missingFactors).toContain("demand"); expect(score.factorScores.demand).toBeUndefined(); });
  it("deduplica, não completa a meta com produtos ruins e persiste o run", async () => { const repository = new MemoryRepository(), service = new ProductResearchService(provider([completeFixture, completeFixture, sparseFixture]), repository); const run = await service.research({ workspaceId: "workspace", queries: ["organização"], targetCandidates: 20 }); expect(run.candidates).toHaveLength(2); expect(run.reasons.MLB1?.length).toBeGreaterThan(0); expect(run.recommended + run.opportunities + run.rejected).toBe(2); expect(repository.runs).toHaveLength(1); });
  it("exige três anúncios equivalentes e prioriza o mais barato quando a qualidade é comparável", async () => { const values = [variant("MLB1", 89), variant("MLB2", 69), variant("MLB3", 79)], repository = new MemoryRepository(), service = new ProductResearchService(provider(values), repository); await service.research({ workspaceId: "workspace", queries: ["organizador"] }); await expect(service.compare("workspace", ["MLB1", "MLB2"])).rejects.toThrow("minimum_three"); const result = await service.compare("workspace", values.map(value => value.externalId)); expect(result.winner?.product.externalId).toBe("MLB2"); });
  it("recusa comparação de produtos não equivalentes", async () => { const values = [variant("MLB1", 89), variant("MLB2", 69), variant("MLB3", 79, { name: "Panela elétrica", categoryExternalId: "OTHER" })], repository = new MemoryRepository(), service = new ProductResearchService(provider(values), repository); await service.research({ workspaceId: "workspace", queries: ["casa"] }); await expect(service.compare("workspace", values.map(value => value.externalId))).rejects.toThrow("products_not_comparable"); });
  it("aceita rating 4.6 de forma contextual e não torna preço fora da faixa uma rejeição automática", () => { const product = variant("MLB4", 25, { rating: 4.6, reviewCount: 200 }); expect(verdictFor(product, scoreCandidate(product, [product]), [product])).not.toBe("NÃO RECOMENDADO"); const premium = variant("MLB5", 650); expect(verdictFor(premium, scoreCandidate(premium, [premium]), [premium])).not.toBe("NÃO RECOMENDADO"); });
  it("classifica produto novo confiável como oportunidade e rejeita quando confiança essencial falta", () => { const fresh = variant("MLB6", 90, { salesCount: 2, reviewCount: 2 }); expect(verdictFor(fresh, scoreCandidate(fresh, [fresh]), [fresh])).toBe("OPORTUNIDADE PARA REVISÃO"); expect(verdictFor(sparseFixture, scoreCandidate(sparseFixture, [sparseFixture]), [sparseFixture])).toBe("NÃO RECOMENDADO"); });
  it("mantém diversidade no peso de categorias", () => { const allocation = allocateCategoryTargets(["Organização", "Cozinha", "Outras"], { Organização: 35, Cozinha: 25, Outras: 40 }, 20); expect(allocation.Organização).toBeGreaterThan(0); expect(allocation.Cozinha).toBeGreaterThan(0); expect(Object.values(allocation).reduce((a, b) => a + b, 0)).toBe(20); });
  it("busca similares apenas para vencedores com venda, sem confundir clique", () => { expect(generateWinnerQueries([{ name: "Cesto", conversions: 0, clicks: 500 }, { name: "Panela", conversions: 2 }])).toEqual(["produtos similares a Panela"]); });
});
