import { OAuthProvider, type OAuthProviderConfig } from "../base/oauth-provider.js";
import type { HttpClient } from "../base/provider.js";
export function createMetaProvider(clientId: string, clientSecret: string, graphApiVersion: string, http: HttpClient, options: { pilotEnabled?: boolean; realPublishingEnabled?: boolean; configurationId?: string } = {}) {
  if (!/^v\d+\.\d+$/.test(graphApiVersion)) throw new Error("invalid_meta_graph_api_version");
  const config: OAuthProviderConfig = { name: "facebook", clientId, clientSecret, authorizationEndpoint: `https://www.facebook.com/${graphApiVersion}/dialog/oauth`, tokenEndpoint: `https://graph.facebook.com/${graphApiVersion}/oauth/access_token`, validationEndpoint: `https://graph.facebook.com/${graphApiVersion}/me?fields=id,name`, revocationEndpoint: `https://graph.facebook.com/${graphApiVersion}/me/permissions`, scopes: ["pages_show_list", "pages_read_engagement", "pages_manage_posts"], capabilities: { read_account: { scope: "pages_show_list" }, list_pages: { scope: "pages_show_list" }, read_page: { scope: "pages_read_engagement" }, create_page_post: { scope: "pages_manage_posts", enabled: options.pilotEnabled === true && options.realPublishingEnabled === true }, create_page_photo: { scope: "pages_manage_posts", enabled: options.pilotEnabled === true && options.realPublishingEnabled === true }, read_page_posts: { scope: "pages_read_engagement" }, create_comment: { scope: "pages_manage_posts", supported: false } }, pkce: true };
  return new MetaOAuthProvider(config, http, options.configurationId);
}

class MetaOAuthProvider extends OAuthProvider { constructor(config:OAuthProviderConfig,http:HttpClient,private readonly configurationId?:string){super(config,http)} override getAuthorizationUrl(context:Parameters<OAuthProvider["getAuthorizationUrl"]>[0]){const url=super.getAuthorizationUrl(context);if(this.configurationId)url.searchParams.set("config_id",this.configurationId);return url} }

export type FacebookPage={id:string;name:string;category:string|null;tasks:string[]};
export type FacebookPageCredential=FacebookPage&{accessToken:string};
export class FacebookPageProvider {
  constructor(private readonly graphApiVersion: string, private readonly http: HttpClient, private readonly accessToken: () => Promise<string>) { if (!/^v\d+\.\d+$/.test(graphApiVersion)) throw new Error("invalid_meta_graph_api_version"); }
  async listPages():Promise<readonly FacebookPage[]>{return(await this.listPageCredentials()).map(({accessToken:_,...page})=>page)}
  async listPageCredentials():Promise<readonly FacebookPageCredential[]>{type PageResponse={data?:Array<{id?:string;name?:string;category?:string;tasks?:string[];access_token?:string}>;paging?:{next?:string}};const token=await this.accessToken(),pages:FacebookPageCredential[]=[],seen=new Set<string>();let next:string|undefined=`https://graph.facebook.com/${this.graphApiVersion}/me/accounts?fields=id,name,category,tasks,access_token&limit=100`;while(next){if(seen.has(next)||seen.size>=100)throw new Error("pages_pagination_incomplete");seen.add(next);const response:PageResponse=await this.http.request<PageResponse>({url:next,method:"GET",headers:{Authorization:`Bearer ${token}`}});if(!Array.isArray(response.data))throw new Error("invalid_pages_response");pages.push(...response.data.filter((page):page is {id:string;name:string;access_token:string;category?:string;tasks?:string[]}=>Boolean(page.id&&page.name&&page.access_token)).map(page=>({id:page.id,name:page.name,category:page.category??null,tasks:Array.isArray(page.tasks)?page.tasks:[],accessToken:page.access_token})));next=response.paging?.next}return pages}
}

export type FacebookPostInput={pageId:string;message:string;link?:string;imageUrl?:string};
export class FacebookPublishingProvider{constructor(private readonly version:string,private readonly http:HttpClient,private readonly pageToken:()=>Promise<string>,private readonly enabled:()=>boolean){}async createPost(input:FacebookPostInput){if(!this.enabled())throw new Error("facebook_publishing_disabled");const token=await this.pageToken(),photo=Boolean(input.imageUrl),url=`https://graph.facebook.com/${this.version}/${input.pageId}/${photo?"photos":"feed"}`,body=photo?{message:input.message,url:input.imageUrl}:{message:input.message,link:input.link};const result=await this.http.request<{id?:string;post_id?:string}>({url,method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const id=result.post_id??result.id;if(!id)throw new Error("reconciliation_required");return{externalId:id,externalUrl:null,publishedAt:new Date(),metadata:{provider:"facebook"}}}}
