import{readFileSync}from"node:fs";import{describe,expect,it,vi}from"vitest";import type{HttpClient}from"../base/provider.js";import{ProviderError}from"../base/provider.js";import{PublicWebProductDiscoverySource,parsePublicProducts}from"./index.js";
const fixture=(name:string)=>readFileSync(new URL(`./fixtures/${name}`,import.meta.url),"utf8");
describe("PublicWebProductDiscoverySource",()=>{
 it("captura somente campos públicos e evidência explícita de vendas",()=>{const[p]=parsePublicProducts(fixture("search.html"),"https://lista.mercadolivre.com.br/organizador",new Date("2026-09-06T12:00:00Z"));expect(p).toMatchObject({externalId:"MLB1234567890",name:"Organizador de Cozinha",price:79.9,currency:"BRL",rating:4.8,reviewCount:321,salesCount:10000,sellerName:"Casa Loja",images:["https://http2.mlstatic.com/test.jpg"],isBestSeller:true,isOfficialStore:true,freeShipping:true});expect(p?.rawSourceReference).toContain("observedAt=2026-09-06")});
 it("mantém dados ausentes como null e não inventa vendedor ou vendas",()=>{const[p]=parsePublicProducts(fixture("missing.html"),"https://lista.mercadolivre.com.br/cesto");expect(p).toMatchObject({price:null,rating:null,reviewCount:null,salesCount:null,sellerName:null,images:[]});expect(p?.missingFields).toEqual(expect.arrayContaining(["price","rating","reviewCount","seller","salesCount","images"]))});
 it("trata HTML alterado como vazio e captcha como fonte indisponível",()=>{expect(parsePublicProducts("<html>mudou</html>","https://example.com")).toEqual([]);expect(()=>parsePublicProducts("<html>Robot Verification CAPTCHA</html>","https://example.com")).toThrow(ProviderError)});
 it("deduplica requests no cache diário curto",async()=>{const request=vi.fn().mockResolvedValue(fixture("search.html")),source=new PublicWebProductDiscoverySource({request}as HttpClient,()=>new Date("2026-09-06T12:00:00Z"));await source.searchProducts({query:"organizador",limit:5});await source.searchProducts({query:"organizador",limit:5});expect(request).toHaveBeenCalledOnce()});
 it("continua outras categorias quando uma fonte retorna 403 ou timeout",async()=>{const request=vi.fn().mockRejectedValueOnce(new ProviderError("CAPABILITY_MISSING",403)).mockResolvedValue(fixture("search.html")),source=new PublicWebProductDiscoverySource({request}as HttpClient);const signals=await source.discover(["cozinha","banheiro"]);expect(signals).toHaveLength(1);expect(request).toHaveBeenCalledTimes(2)});
});
