import { z } from "zod";

export const metricAvailabilitySchema = z.enum(["available", "zero", "not_applicable", "unknown", "unavailable"]);
export const dataProvenanceSchema=z.object({source:z.string().min(1),capturedAt:z.coerce.date(),availability:metricAvailabilitySchema,freshness:z.enum(["fresh","stale","unknown"]),confidence:z.number().min(0).max(1)});
export type DataProvenance=z.infer<typeof dataProvenanceSchema>;
export const metricSourceSchema = z.enum(["manual", "pinterest", "meta", "affiliate", "imported"]);
export const analyticsPlatformSchema = z.enum(["pinterest", "facebook", "business"]);
export const metricNameSchema = z.enum(["impressions", "reach", "saves", "pinClicks", "outboundClicks", "reactions", "comments", "shares", "clicks", "videoViews", "engagement", "affiliateClicks", "conversions", "sales", "revenue", "commission"]);
const nullableId = z.string().min(1).nullable().default(null);
export const platformMetricInputSchema = z.object({ platform: analyticsPlatformSchema, source: metricSourceSchema, metricName: metricNameSchema, value: z.number().nonnegative().nullable(), capturedAt: z.coerce.date(), periodStart: z.coerce.date(), periodEnd: z.coerce.date(), externalEntityId: nullableId, publicationId: nullableId, productId: nullableId, contentId: nullableId, categoryId: nullableId, availability: metricAvailabilitySchema, confidence: z.number().min(0).max(1).default(1), metadata: z.record(z.string(), z.unknown()).default({}) }).superRefine((metric, context) => { if (metric.periodEnd < metric.periodStart) context.addIssue({ code: "custom", message: "period_end_before_start" }); if (metric.availability === "zero" && metric.value !== 0) context.addIssue({ code: "custom", message: "zero_requires_zero_value" }); if (metric.availability === "available" && metric.value === null) context.addIssue({ code: "custom", message: "available_requires_value" }); if (["unknown", "unavailable", "not_applicable"].includes(metric.availability) && metric.value !== null) context.addIssue({ code: "custom", message: "unavailable_metric_must_not_have_value" }); });
export const normalizedMetricSchema = platformMetricInputSchema.extend({ normalizedAt: z.coerce.date() });
export const metricSnapshotInputSchema = z.object({ metrics: z.array(platformMetricInputSchema).min(1), importedAt: z.coerce.date().default(() => new Date()) });
export const performanceScoreSchema = z.object({ score: z.number().min(0).max(100).nullable(), confidence: z.number().min(0).max(1), availableSignals: z.array(z.string()), missingSignals: z.array(z.string()), components: z.record(z.string(), z.number()), explanation: z.string() });
export const performanceClassificationSchema = z.enum(["WINNER", "PROMISING", "NEUTRAL", "WEAK", "INSUFFICIENT_DATA"]);
export const derivedKpiSchema = z.object({ value: z.number().nullable(), availability: z.enum(["available", "zero", "not_applicable", "unknown", "unavailable"]), numerator: z.string(), denominator: z.string(), explanation: z.string() });
export const performanceInsightSchema = z.object({ type: z.enum(["WINNER", "UNDERPERFORMER", "OPPORTUNITY", "SATURATION", "DATA_GAP", "ANOMALY", "CATEGORY_SIGNAL", "CREATIVE_SIGNAL", "TIMING_SIGNAL"]), severity: z.enum(["info", "warning", "critical"]), entityType: z.string(), entityId: z.string().nullable(), title: z.string(), explanation: z.string(), evidence: z.array(z.string()), confidence: z.number().min(0).max(1), recommendedAction: z.string() });
export const analyticsPeriodSchema = z.object({ start: z.coerce.date(), end: z.coerce.date() }).refine(value => value.end >= value.start, "period_end_before_start");
export const analyticsFilterSchema = z.object({ platform: analyticsPlatformSchema.optional(), productId: z.string().min(1).optional(), categoryId: z.string().min(1).optional(), publicationId: z.string().min(1).optional(), creativeAssetId: z.string().min(1).optional() });
export const anomalySchema = z.object({ metricName: metricNameSchema, type: z.enum(["unusual_spike", "unusual_drop"]), latest: z.number(), baseline: z.number(), confidence: z.number().min(0).max(1) });
export const dataQualityReportSchema = z.object({ coverage: z.number().min(0).max(1), availableMetrics: z.number().int().nonnegative(), unavailableMetrics: z.number().int().nonnegative(), byAvailability: z.record(metricAvailabilitySchema, z.number().int().nonnegative()), duplicates: z.number().int().nonnegative(), partialPeriod: z.boolean(), freshestAt: z.coerce.date().nullable(), staleSource: z.boolean(), anomalies: z.array(anomalySchema), warnings: z.array(z.string()) });
export type PlatformMetricInput = z.input<typeof platformMetricInputSchema>;
export type NormalizedMetric = z.infer<typeof normalizedMetricSchema>;
export type MetricSnapshotInput = z.input<typeof metricSnapshotInputSchema>;
export type MetricAvailability = z.infer<typeof metricAvailabilitySchema>;
export type MetricSource = z.infer<typeof metricSourceSchema>;
export type PerformanceScore = z.infer<typeof performanceScoreSchema>;
export type PerformanceInsight = z.infer<typeof performanceInsightSchema>;
export type AnalyticsPeriod = z.infer<typeof analyticsPeriodSchema>;
export type AnalyticsFilter = z.infer<typeof analyticsFilterSchema>;
export type DerivedKpi = z.infer<typeof derivedKpiSchema>;
export type DataQualityReport = z.infer<typeof dataQualityReportSchema>;
