import { z } from "zod";
import { contentAngleSchema } from "./content.js";

export const creativeFormatSchema = z.enum(["PINTEREST_2_3", "FACEBOOK_4_5", "FACEBOOK_1_1"]);
export const creativeTemplateSchema = z.enum(["MINIMAL_OVERLAY", "BOTTOM_INFO_PANEL", "TOP_HEADLINE", "SIDE_INFO", "PHOTO_FIRST"]);
export const brandPlacementSchema = z.enum(["BOTTOM_RIGHT", "BOTTOM_LEFT", "TOP_RIGHT", "TOP_LEFT"]);
export const creativeStatusSchema = z.enum(["DRAFT", "READY", "NEEDS_REVIEW", "BLOCKED_FOR_PRICE_REFRESH"]);
export const brandKitSchema = z.object({ version: z.string(), colors: z.object({ primary: z.string(), background: z.string(), secondary: z.string(), text: z.string(), accent: z.string() }), fonts: z.object({ display: z.string(), support: z.string() }), brandPlacement: brandPlacementSchema });
export const DEFAULT_BRAND_KIT = brandKitSchema.parse({ version: "1", colors: { primary: "#3F5948", background: "#F6F1E7", secondary: "#829780", text: "#292D2A", accent: "#C98268" }, fonts: { display: "Merriweather, Georgia, serif", support: "Manrope, Arial, sans-serif" }, brandPlacement: "BOTTOM_RIGHT" });
export const productImageCandidateSchema = z.object({ imageUrl: z.string().min(1), sourceUrl: z.string().min(1), sourceProvider: z.string(), externalProductId: z.string(), imageHash: z.string().nullable(), width: z.number().int().positive(), height: z.number().int().positive(), mimeType: z.string(), capturedAt: z.coerce.date(), assetSource: z.enum(["MARKETPLACE_PRODUCT_IMAGE", "USER_UPLOADED", "GENERATED_BACKGROUND", "INTERNAL_BRAND_ASSET"]), usageStatus: z.enum(["UNKNOWN", "ALLOWED", "RESTRICTED"]), hasConflictingText: z.boolean().default(false), productVisible: z.boolean().default(true), focusScore: z.number().min(0).max(1).default(.8), lightingScore: z.number().min(0).max(1).default(.8), visualNoiseScore: z.number().min(0).max(1).default(.2), overlaySpaceScore: z.number().min(0).max(1).default(.5), usageDemonstration: z.boolean().default(false) });
export const productImageAnalysisSchema = z.object({ imageUrl: z.string(), score: z.number().min(0).max(100), strengths: z.array(z.string()), risks: z.array(z.string()), selectionReason: z.string() });
export const productImageSelectionSchema = z.object({ primaryImage: productImageAnalysisSchema.nullable(), alternateImages: z.array(productImageAnalysisSchema), creativeStatus: creativeStatusSchema, reason: z.string() });
export const creativeTextOverlaySchema = z.object({ kind: z.enum(["PRODUCT_NAME", "FACT", "SAFE_BENEFIT", "PRICE", "BRAND"]), text: z.string().min(1).max(80), confirmed: z.boolean(), x: z.number().min(0).max(1), y: z.number().min(0).max(1), maxWidth: z.number().min(0).max(1) });
export const creativeLayoutSchema = z.object({ template: creativeTemplateSchema, width: z.number().int().positive(), height: z.number().int().positive(), safeCrop: z.object({ strategy: z.literal("contain"), preserveProduct: z.literal(true), criticalAreaCovered: z.boolean() }), contrastRatio: z.number().min(1), overlayBackground: z.boolean() });
export const creativeRequestSchema = z.object({ workspaceId: z.string(), productId: z.string(), contentId: z.string(), platform: z.enum(["pinterest", "facebook"]), format: creativeFormatSchema, template: creativeTemplateSchema.default("PHOTO_FIRST"), variantCount: z.number().int().min(1).max(3).default(1), productName: z.string().min(1), confirmedFacts: z.array(z.string().max(40)).max(2), safeBenefits: z.array(z.string().max(60)).max(2), price: z.number().positive().nullable(), priceCheckedAt: z.coerce.date().nullable(), priceRequested: z.boolean(), images: z.array(productImageCandidateSchema).min(1) });
export const creativeValidationResultSchema = z.object({ valid: z.boolean(), errors: z.array(z.string()), warnings: z.array(z.string()) });
export const creativeOutputSchema = z.object({ platform: z.enum(["pinterest", "facebook"]), size: z.object({ width: z.number(), height: z.number() }), primaryImage: productImageAnalysisSchema.nullable(), layout: creativeLayoutSchema, overlays: z.array(creativeTextOverlaySchema), brandPlacement: brandPlacementSchema, price: z.number().nullable(), validation: creativeValidationResultSchema, status: creativeStatusSchema, previewReference: z.string().nullable(), metadata: z.record(z.string(), z.unknown()) });
export const creativeVariantSchema = z.object({ objective: z.string(), contentAngle: contentAngleSchema, layout: creativeTemplateSchema, image: z.string(), overlayText: z.array(z.string()) });
export type ProductImageCandidate = z.infer<typeof productImageCandidateSchema>; export type ProductImageAnalysis = z.infer<typeof productImageAnalysisSchema>; export type ProductImageSelection = z.infer<typeof productImageSelectionSchema>; export type CreativeRequest = z.infer<typeof creativeRequestSchema>; export type CreativeOutput = z.infer<typeof creativeOutputSchema>; export type CreativeValidationResult = z.infer<typeof creativeValidationResultSchema>; export type CreativeVariant = z.infer<typeof creativeVariantSchema>; export type BrandKit = z.infer<typeof brandKitSchema>;
