import { describe, expect, it, vi } from "vitest";
import { z } from "zod";
import { registerContentOperationsTools, registerContentTools, registerCreativeStudioTools, registerFacebookStrategyTools, registerPinterestStrategyTools, registerProductResearchTools, ToolRegistry, type ContentOperationsToolService, type ContentToolService, type CreativeStudioToolService, type FacebookStrategyToolService, type PinterestStrategyToolService, type ProductResearchToolService } from "./tool-registry.js";
describe("ToolRegistry", () => {
  it("validates and calls an application service-backed tool", async () => { const execute = vi.fn(async ({ id }: { id: string }) => ({ id })); const registry = new ToolRegistry(); registry.register({ name: "lookup", description: "lookup", parameters: z.object({ id: z.string() }), externalAction: false, execute }); await expect(registry.execute("lookup", { id: "p1" })).resolves.toEqual({ id: "p1" }); expect(execute).toHaveBeenCalledOnce(); });
  it("propagates a tool failure without fabricating a result", async () => { const registry = new ToolRegistry(); registry.register({ name: "failing", description: "fails", parameters: z.object({}), externalAction: false, execute: async () => { throw new Error("repository_unavailable"); } }); await expect(registry.execute("failing", {})).rejects.toThrow("repository_unavailable"); });
  it("registers the complete product research surface without publication approval", () => { const registry = new ToolRegistry(); const service = { research: vi.fn(), getProductDetails: vi.fn(), compare: vi.fn(), calculateStored: vi.fn(), listRuns: vi.fn(), approve: vi.fn(), reject: vi.fn() } as unknown as ProductResearchToolService; registerProductResearchTools(registry, service, "workspace"); expect(registry.list().map(tool => tool.name)).toEqual(["search_products", "get_product_details", "compare_products", "calculate_product_score", "list_research_runs", "recommend_product", "reject_product"]); expect(registry.list().some(tool => tool.name === "approve_product")).toBe(false); });
  it("registers all content tools as non-publishing operations", () => { const registry = new ToolRegistry(), service = { generateProduct: vi.fn(), generateUtility: vi.fn(), listProductContent: vi.fn(), getContentHistory: vi.fn(), createVariant: vi.fn() } as unknown as ContentToolService; registerContentTools(registry, service, "w1"); expect(registry.list().map(tool => tool.name)).toEqual(["generate_pinterest_content", "generate_facebook_content", "generate_utility_content", "list_product_content", "create_content_variant", "get_content_history"]); expect(registry.list().every(tool => !tool.externalAction)).toBe(true); });
  it("registers Pinterest strategy tools without a publish operation", () => { const registry = new ToolRegistry(), service = { createWeeklyStrategy: vi.fn(), createDailyPlan: vi.fn(), recommendBoard: vi.fn(), generateKeywords: vi.fn(), preparePin: vi.fn(), listBoards: vi.fn(), getStrategy: vi.fn(), getContentHistory: vi.fn() } as unknown as PinterestStrategyToolService; registerPinterestStrategyTools(registry, service, "w1"); expect(registry.list().map(tool => tool.name)).toEqual(["create_pinterest_strategy", "create_daily_pinterest_plan", "recommend_pinterest_board", "generate_pinterest_keywords", "prepare_pinterest_pin", "list_pinterest_boards", "get_pinterest_strategy", "get_pinterest_content_history"]); expect(registry.list().some(tool => tool.name === "publish_pin")).toBe(false); });
  it("registers Facebook strategy tools without publishing", () => { const registry = new ToolRegistry(), service = { createWeeklyStrategy: vi.fn(), createDailyPlan: vi.fn(), preparePost: vi.fn(), prepareStoredComment: vi.fn(), evaluateStoredReuse: vi.fn(), getStrategy: vi.fn(), getContentHistory: vi.fn(), listPages: vi.fn() } as unknown as FacebookStrategyToolService; registerFacebookStrategyTools(registry, service, "w1"); expect(registry.list().map(tool => tool.name)).toEqual(["create_facebook_strategy", "create_daily_facebook_plan", "prepare_facebook_post", "prepare_facebook_comment", "evaluate_facebook_reuse", "get_facebook_strategy", "get_facebook_content_history", "list_facebook_pages"]); expect(registry.list().some(tool => tool.name.includes("publish"))).toBe(false); });
  it("registers Creative Studio tools as non-publishing operations", () => { const registry = new ToolRegistry(), service = { request: vi.fn(), analyze: vi.fn(), select: vi.fn(), preview: vi.fn(), render: vi.fn(), variants: vi.fn(), validate: vi.fn(), getProductCreatives: vi.fn() } as unknown as CreativeStudioToolService; registerCreativeStudioTools(registry, service, "w1"); expect(registry.list().map(tool => tool.name)).toEqual(["analyze_product_images", "select_best_product_image", "create_creative_preview", "render_product_creative", "create_creative_variants", "validate_creative", "get_product_creatives"]); expect(registry.list().every(tool => !tool.externalAction)).toBe(true); });
  it("executes a Creative Studio tool through the typed request without publishing", async () => { const loaded = { productId: "p1" } as unknown as Awaited<ReturnType<CreativeStudioToolService["request"]>>; const service = { request: vi.fn().mockResolvedValue(loaded), analyze: vi.fn().mockReturnValue([{ score: 91 }]), select: vi.fn(), preview: vi.fn(), render: vi.fn(), variants: vi.fn(), validate: vi.fn(), getProductCreatives: vi.fn() } as unknown as CreativeStudioToolService; const registry = new ToolRegistry(); registerCreativeStudioTools(registry, service, "w1"); await expect(registry.execute("analyze_product_images", { productId: "p1", contentId: "c1", platform: "pinterest", format: "PINTEREST_2_3", template: "PHOTO_FIRST", variantCount: 1 })).resolves.toEqual([{ score: 91 }]); expect(service.request).toHaveBeenCalledWith("w1", "p1", expect.objectContaining({ contentId: "c1" })); expect(service.analyze).toHaveBeenCalledWith(loaded); });
  it("registers content operations and blocks human/external actions from agent execution", async () => { const service = { run: vi.fn().mockResolvedValue({ approvalsRequired: true }), listQueue: vi.fn(), approve: vi.fn(), reject: vi.fn(), approveBatch: vi.fn(), schedule: vi.fn(), publishNow: vi.fn(), cancel: vi.fn(), retry: vi.fn(), status: vi.fn(), alerts: vi.fn() } as unknown as ContentOperationsToolService, registry = new ToolRegistry(); registerContentOperationsTools(registry, service); expect(registry.list().map(x => x.name)).toEqual(["run_daily_operations", "list_publication_queue", "approve_publication_item", "reject_publication_item", "approve_publication_batch", "schedule_publication", "publish_now", "cancel_publication", "retry_publication", "get_publication_status", "list_operational_alerts"]); await expect(registry.execute("run_daily_operations", { date: "2026-09-04" })).resolves.toMatchObject({ approvalsRequired: true }); await expect(registry.execute("publish_now", { id: "q1", actorId: "u1" })).rejects.toThrow("approval_required:publish_now"); expect(service.publishNow).not.toHaveBeenCalled(); });
});
