import { describe, expect, it, vi } from "vitest";
import { z } from "zod";
import { registerContentTools, registerPinterestStrategyTools, registerProductResearchTools, ToolRegistry, type ContentToolService, type PinterestStrategyToolService, type ProductResearchToolService } from "./tool-registry.js";
describe("ToolRegistry", () => {
  it("validates and calls an application service-backed tool", async () => { const execute = vi.fn(async ({ id }: { id: string }) => ({ id })); const registry = new ToolRegistry(); registry.register({ name: "lookup", description: "lookup", parameters: z.object({ id: z.string() }), externalAction: false, execute }); await expect(registry.execute("lookup", { id: "p1" })).resolves.toEqual({ id: "p1" }); expect(execute).toHaveBeenCalledOnce(); });
  it("propagates a tool failure without fabricating a result", async () => { const registry = new ToolRegistry(); registry.register({ name: "failing", description: "fails", parameters: z.object({}), externalAction: false, execute: async () => { throw new Error("repository_unavailable"); } }); await expect(registry.execute("failing", {})).rejects.toThrow("repository_unavailable"); });
  it("registers the complete product research surface without publication approval", () => { const registry = new ToolRegistry(); const service = { research: vi.fn(), getProductDetails: vi.fn(), compare: vi.fn(), calculateStored: vi.fn(), listRuns: vi.fn(), approve: vi.fn(), reject: vi.fn() } as unknown as ProductResearchToolService; registerProductResearchTools(registry, service, "workspace"); expect(registry.list().map(tool => tool.name)).toEqual(["search_products", "get_product_details", "compare_products", "calculate_product_score", "list_research_runs", "recommend_product", "reject_product"]); expect(registry.list().some(tool => tool.name === "approve_product")).toBe(false); });
  it("registers all content tools as non-publishing operations", () => { const registry = new ToolRegistry(), service = { generateProduct: vi.fn(), generateUtility: vi.fn(), listProductContent: vi.fn(), getContentHistory: vi.fn(), createVariant: vi.fn() } as unknown as ContentToolService; registerContentTools(registry, service, "w1"); expect(registry.list().map(tool => tool.name)).toEqual(["generate_pinterest_content", "generate_facebook_content", "generate_utility_content", "list_product_content", "create_content_variant", "get_content_history"]); expect(registry.list().every(tool => !tool.externalAction)).toBe(true); });
  it("registers Pinterest strategy tools without a publish operation", () => { const registry = new ToolRegistry(), service = { createWeeklyStrategy: vi.fn(), createDailyPlan: vi.fn(), recommendBoard: vi.fn(), generateKeywords: vi.fn(), preparePin: vi.fn(), listBoards: vi.fn(), getStrategy: vi.fn(), getContentHistory: vi.fn() } as unknown as PinterestStrategyToolService; registerPinterestStrategyTools(registry, service, "w1"); expect(registry.list().map(tool => tool.name)).toEqual(["create_pinterest_strategy", "create_daily_pinterest_plan", "recommend_pinterest_board", "generate_pinterest_keywords", "prepare_pinterest_pin", "list_pinterest_boards", "get_pinterest_strategy", "get_pinterest_content_history"]); expect(registry.list().some(tool => tool.name === "publish_pin")).toBe(false); });
});
