import { z } from "zod";
import type { CreativeRequest } from "@casapratica/domain";
import type { TraceRepository } from "./contracts.js";

export interface RegisteredTool<TSchema extends z.ZodObject<z.ZodRawShape> = z.ZodObject<z.ZodRawShape>> {
  readonly name: string;
  readonly description: string;
  readonly parameters: TSchema;
  readonly externalAction: boolean;
  execute(input: z.infer<TSchema>): Promise<unknown>;
}

export class ToolRegistry {
  readonly #tools = new Map<string, RegisteredTool>();
  constructor(private readonly traces?: TraceRepository) {}
  register<TSchema extends z.ZodObject<z.ZodRawShape>>(tool: RegisteredTool<TSchema>): void {
    if (this.#tools.has(tool.name)) throw new Error(`Tool already registered: ${tool.name}`);
    this.#tools.set(tool.name, tool);
  }
  get(name: string): RegisteredTool {
    const tool = this.#tools.get(name);
    if (!tool) throw new Error(`Unknown tool: ${name}`);
    return tool;
  }
  list(): readonly RegisteredTool[] { return [...this.#tools.values()]; }
  async execute(name: string, input: unknown, agent = "CasaPraticaManagerAgent"): Promise<unknown> {
    const registered = this.get(name);
    if (registered.externalAction) throw new Error(`approval_required:${name}`);
    const startedAt = performance.now();
    try {
      const result = await registered.execute(registered.parameters.parse(input));
      await this.traces?.append({ agent, tool: name, durationMs: performance.now() - startedAt, status: "succeeded", errorCode: null, usage: null });
      return result;
    } catch (error) {
      await this.traces?.append({ agent, tool: name, durationMs: performance.now() - startedAt, status: "failed", errorCode: error instanceof Error ? error.message : "unknown_error", usage: null });
      throw error;
    }
  }
}

export interface ProductQueryService { findFacts(productId: string): Promise<unknown> }
export interface PerformanceQueryService { diagnose(from: string, to: string): Promise<unknown> }
export function registerOperationalTools(registry: ToolRegistry, services: { products: ProductQueryService; performance: PerformanceQueryService }): void {
  registry.register({ name: "get_product_facts", description: "Read verified product facts through the application service.", parameters: z.object({ productId: z.string() }), externalAction: false, execute: ({ productId }) => services.products.findFacts(productId) });
  registry.register({ name: "get_performance_metrics", description: "Read persisted performance metrics through the application service.", parameters: z.object({ from: z.string(), to: z.string() }), externalAction: false, execute: ({ from, to }) => services.performance.diagnose(from, to) });
}
export interface AnalyticsToolService { overview(w:string,p:{start:Date;end:Date}):Promise<unknown>; winners(w:string,p:{start:Date;end:Date}):Promise<unknown>; underperformers(w:string,p:{start:Date;end:Date}):Promise<unknown>; insights(w:string,p:{start:Date;end:Date}):Promise<unknown>; dataQuality(w:string,p:{start:Date;end:Date}):Promise<unknown>; daily(w:string,p:{start:Date;end:Date}):Promise<unknown>; weekly(w:string,p:{start:Date;end:Date}):Promise<unknown> }
export function registerAnalyticsTools(registry:ToolRegistry,service:AnalyticsToolService,workspaceId:string):void { const period=z.object({from:z.coerce.date(),to:z.coerce.date()}); const call=(fn:(w:string,p:{start:Date;end:Date})=>Promise<unknown>)=>({from,to}:z.infer<typeof period>)=>fn.call(service,workspaceId,{start:from,end:to}); for(const [name,description,fn] of [["get_analytics_overview","Consulta métricas e KPIs sem inferir dados.",service.overview],["get_performance_winners","Lista vencedores/promissores somente com amostra suficiente.",service.winners],["get_underperformers","Lista sinais fracos para diagnóstico, sem alterar estratégia.",service.underperformers],["get_performance_insights","Obtém insights explicáveis.",service.insights],["get_data_quality_report","Audita cobertura, disponibilidade, duplicatas e anomalias.",service.dataQuality],["get_daily_analytics_summary","Gera resumo diário somente leitura.",service.daily],["get_weekly_analytics_review","Gera revisão semanal com experimentos.",service.weekly]] as const)registry.register({name,description,parameters:period,externalAction:false,execute:call(fn)}); }

export interface ProductResearchToolService {
  research(input: { workspaceId: string; queries: readonly string[]; categories?: readonly string[]; targetCandidates?: number }): Promise<unknown>;
  getProductDetails(externalId: string): Promise<unknown>;
  compare(workspaceId: string, externalIds: readonly string[]): Promise<unknown>;
  calculateStored(workspaceId: string, externalId: string): Promise<unknown>;
  listRuns(workspaceId: string): Promise<unknown>;
  approve(workspaceId: string, externalId: string, reason: string): Promise<void>;
  reject(workspaceId: string, externalId: string, reason: string): Promise<void>;
}
export function registerProductResearchTools(registry: ToolRegistry, service: ProductResearchToolService, workspaceId: string): void {
  registry.register({ name: "search_products", description: "Pesquisa produtos reais no provider e executa normalização, deduplicação, elegibilidade, score e ranking. Para a pesquisa diária, solicite até 20 candidatos sem completar com itens inelegíveis.", parameters: z.object({ queries: z.array(z.string().min(1)).default([]), categories: z.array(z.string().min(1)).default([]), targetCandidates: z.number().int().min(1).max(20).default(20) }), externalAction: false, execute: input => service.research({ workspaceId, ...input }) });
  registry.register({ name: "get_product_details", description: "Obtém detalhes atuais de um produto no provider oficial.", parameters: z.object({ externalId: z.string().min(1) }), externalAction: false, execute: ({ externalId }) => service.getProductDetails(externalId) });
  registry.register({ name: "compare_products", description: "Compara pelo menos três candidatos equivalentes e registra o motivo do vencedor.", parameters: z.object({ externalIds: z.array(z.string().min(1)).min(3) }), externalAction: false, execute: ({ externalIds }) => service.compare(workspaceId, externalIds) });
  registry.register({ name: "calculate_product_score", description: "Retorna o score persistido com confiança e fatores ausentes explícitos.", parameters: z.object({ externalId: z.string().min(1) }), externalAction: false, execute: ({ externalId }) => service.calculateStored(workspaceId, externalId) });
  registry.register({ name: "list_research_runs", description: "Lista execuções de pesquisa persistidas do workspace.", parameters: z.object({}), externalAction: false, execute: () => service.listRuns(workspaceId) });
  registry.register({ name: "recommend_product", description: "Registra que o proprietário recomendou o produto para seguir ao fluxo de conteúdo. Não aprova publicação.", parameters: z.object({ externalId: z.string().min(1), reason: z.string().min(3) }), externalAction: false, execute: ({ externalId, reason }) => service.approve(workspaceId, externalId, reason) });
  registry.register({ name: "reject_product", description: "Rejeita internamente um produto candidato com motivo explícito.", parameters: z.object({ externalId: z.string().min(1), reason: z.string().min(3) }), externalAction: false, execute: ({ externalId, reason }) => service.reject(workspaceId, externalId, reason) });
}

type ContentToolAngle = "utility" | "problem_solution" | "space_saving" | "organization" | "price_opportunity" | "social_proof" | "comparison" | "seasonal" | "practicality" | "small_home";
export interface ContentToolService {
  generateProduct(input: { workspaceId: string; productId: string; platforms: readonly ("pinterest" | "facebook")[]; variants: number; angles?: readonly ContentToolAngle[] }): Promise<unknown>;
  generateUtility(input: { workspaceId: string; platform: "pinterest" | "facebook"; topic: string; angle?: ContentToolAngle; seasonalContext?: string | null }): Promise<unknown>;
  listProductContent(workspaceId: string, productId: string): Promise<unknown>;
  getContentHistory(workspaceId: string, productId?: string): Promise<unknown>;
  createVariant(workspaceId: string, contentId: string, variant: { platform: "pinterest" | "facebook"; title: string | null; body: string; metadata: Readonly<Record<string, unknown>> }): Promise<unknown>;
}
const contentAngle = z.enum(["utility", "problem_solution", "space_saving", "organization", "price_opportunity", "social_proof", "comparison", "seasonal", "practicality", "small_home"]);
export function registerContentTools(registry: ToolRegistry, service: ContentToolService, workspaceId: string): void {
  const generate = (platform: "pinterest" | "facebook") => ({ productId, variants, angles }: { productId: string; variants: number; angles: ContentToolAngle[] }) => service.generateProduct({ workspaceId, productId, platforms: [platform], variants, angles });
  const productParameters = z.object({ productId: z.string().min(1), variants: z.number().int().min(1).max(3).default(1), angles: z.array(contentAngle).default([]) });
  registry.register({ name: "generate_pinterest_content", description: "Gera Pins estruturados e distintos a partir de fatos confirmados.", parameters: productParameters, externalAction: false, execute: generate("pinterest") });
  registry.register({ name: "generate_facebook_content", description: "Gera conteúdo estruturado para Facebook; links de produto ficam em comentário por padrão.", parameters: productParameters, externalAction: false, execute: generate("facebook") });
  registry.register({ name: "generate_utility_content", description: "Gera conteúdo útil sem exigir produto ou link afiliado.", parameters: z.object({ platform: z.enum(["pinterest", "facebook"]), topic: z.string().min(3), angle: contentAngle.default("utility"), seasonalContext: z.string().nullable().default(null) }), externalAction: false, execute: input => service.generateUtility({ workspaceId, ...input }) });
  registry.register({ name: "list_product_content", description: "Lista histórico de conteúdo de um produto.", parameters: z.object({ productId: z.string().min(1) }), externalAction: false, execute: ({ productId }) => service.listProductContent(workspaceId, productId) });
  registry.register({ name: "create_content_variant", description: "Cria uma variante draft validada; nunca publica.", parameters: z.object({ contentId: z.string().min(1), platform: z.enum(["pinterest", "facebook"]), title: z.string().nullable(), body: z.string().min(20), metadata: z.record(z.string(), z.unknown()) }), externalAction: false, execute: ({ contentId, ...variant }) => service.createVariant(workspaceId, contentId, variant) });
  registry.register({ name: "get_content_history", description: "Consulta histórico recente para evitar repetição.", parameters: z.object({ productId: z.string().optional() }), externalAction: false, execute: ({ productId }) => service.getContentHistory(workspaceId, productId) });
}

export interface PinterestStrategyToolService { createWeeklyStrategy(workspaceId: string, start: Date, seasonalContext?: string | null): Promise<unknown>; createDailyPlan(workspaceId: string, date: Date, requestedPins?: number): Promise<unknown>; recommendBoard(input: { category?: string | null; keywords?: readonly string[]; content?: string }): unknown; generateKeywords(topic: string): unknown; preparePin(workspaceId: string, contentId: string): Promise<unknown>; listBoards(workspaceId: string): Promise<unknown>; getStrategy(workspaceId: string): Promise<unknown>; getContentHistory(workspaceId: string): Promise<unknown> }
export function registerPinterestStrategyTools(registry: ToolRegistry, service: PinterestStrategyToolService, workspaceId: string): void {
  registry.register({ name: "create_pinterest_strategy", description: "Cria estratégia semanal estruturada sem executar ações externas.", parameters: z.object({ start: z.coerce.date(), seasonalContext: z.string().nullable().optional() }), externalAction: false, execute: ({ start, seasonalContext }) => service.createWeeklyStrategy(workspaceId, start, seasonalContext) });
  registry.register({ name: "create_daily_pinterest_plan", description: "Cria plano diário com teto de 10 Pins, reduzido pela qualidade disponível.", parameters: z.object({ date: z.coerce.date(), requestedPins: z.number().int().min(1).max(10).default(10) }), externalAction: false, execute: ({ date, requestedPins }) => service.createDailyPlan(workspaceId, date, requestedPins) });
  registry.register({ name: "recommend_pinterest_board", description: "Recomenda board por categoria, keywords e intenção; não cria boards.", parameters: z.object({ category: z.string().nullable().optional(), keywords: z.array(z.string()).default([]), content: z.string().optional() }), externalAction: false, execute: async ({ category, keywords, content }) => service.recommendBoard({ keywords, ...(category !== undefined ? { category } : {}), ...(content !== undefined ? { content } : {}) }) });
  registry.register({ name: "generate_pinterest_keywords", description: "Gera cluster de keywords e intenção de busca estruturados.", parameters: z.object({ topic: z.string().min(2) }), externalAction: false, execute: async ({ topic }) => service.generateKeywords(topic) });
  registry.register({ name: "prepare_pinterest_pin", description: "Valida e prepara um Pin em awaiting_approval; não publica.", parameters: z.object({ contentId: z.string().min(1) }), externalAction: false, execute: ({ contentId }) => service.preparePin(workspaceId, contentId) });
  registry.register({ name: "list_pinterest_boards", description: "Lista boards reais somente quando OAuth e read_boards estiverem disponíveis.", parameters: z.object({}), externalAction: false, execute: () => service.listBoards(workspaceId) });
  registry.register({ name: "get_pinterest_strategy", description: "Obtém a estratégia Pinterest ativa.", parameters: z.object({}), externalAction: false, execute: () => service.getStrategy(workspaceId) });
  registry.register({ name: "get_pinterest_content_history", description: "Consulta conteúdo Pinterest para prevenir duplicação.", parameters: z.object({}), externalAction: false, execute: () => service.getContentHistory(workspaceId) });
}

export interface FacebookStrategyToolService { createWeeklyStrategy(workspaceId: string, start: Date, seasonalContext?: string | null): Promise<unknown>; createDailyPlan(workspaceId: string, date: Date, requestedPosts?: number): Promise<unknown>; preparePost(workspaceId: string, contentId: string): Promise<unknown>; prepareStoredComment(workspaceId: string, contentId: string): Promise<unknown>; evaluateStoredReuse(workspaceId: string, productId: string, proposedAngle?: ContentToolAngle): Promise<unknown>; getStrategy(workspaceId: string): Promise<unknown>; getContentHistory(workspaceId: string): Promise<unknown>; listPages(workspaceId: string): Promise<unknown> }
export function registerFacebookStrategyTools(registry: ToolRegistry, service: FacebookStrategyToolService, workspaceId: string): void {
  registry.register({ name: "create_facebook_strategy", description: "Cria estratégia semanal estruturada, com mix configurável e sem publicar.", parameters: z.object({ start: z.coerce.date(), seasonalContext: z.string().nullable().optional() }), externalAction: false, execute: ({ start, seasonalContext }) => service.createWeeklyStrategy(workspaceId, start, seasonalContext) });
  registry.register({ name: "create_daily_facebook_plan", description: "Cria plano diário de qualidade com teto de 20 posts, não uma meta.", parameters: z.object({ date: z.coerce.date(), requestedPosts: z.number().int().min(1).max(20).default(4) }), externalAction: false, execute: ({ date, requestedPosts }) => service.createDailyPlan(workspaceId, date, requestedPosts) });
  registry.register({ name: "prepare_facebook_post", description: "Valida e prepara post em awaiting_approval; nunca publica.", parameters: z.object({ contentId: z.string().min(1) }), externalAction: false, execute: ({ contentId }) => service.preparePost(workspaceId, contentId) });
  registry.register({ name: "prepare_facebook_comment", description: "Prepara o comentário afiliado para ação humana; não afirma publicação.", parameters: z.object({ contentId: z.string().min(1) }), externalAction: false, execute: ({ contentId }) => service.prepareStoredComment(workspaceId, contentId) });
  registry.register({ name: "evaluate_facebook_reuse", description: "Avalia histórico, duplicidade e nova razão editorial antes de reutilizar produto.", parameters: z.object({ productId: z.string().min(1), proposedAngle: contentAngle.optional() }), externalAction: false, execute: ({ productId, proposedAngle }) => service.evaluateStoredReuse(workspaceId, productId, proposedAngle) });
  registry.register({ name: "get_facebook_strategy", description: "Obtém a estratégia Facebook ativa e validada.", parameters: z.object({}), externalAction: false, execute: () => service.getStrategy(workspaceId) });
  registry.register({ name: "get_facebook_content_history", description: "Consulta histórico Facebook para evitar repetição.", parameters: z.object({}), externalAction: false, execute: () => service.getContentHistory(workspaceId) });
  registry.register({ name: "list_facebook_pages", description: "Lista páginas reais somente com OAuth e read_page disponíveis.", parameters: z.object({}), externalAction: false, execute: () => service.listPages(workspaceId) });
}

type CreativeInput = { contentId: string; platform: "pinterest" | "facebook"; format: "PINTEREST_2_3" | "FACEBOOK_4_5" | "FACEBOOK_1_1"; template: "MINIMAL_OVERLAY" | "BOTTOM_INFO_PANEL" | "TOP_HEADLINE" | "SIDE_INFO" | "PHOTO_FIRST"; variantCount: number };
export interface CreativeStudioToolService { request(workspaceId: string, productId: string, input: CreativeInput): Promise<CreativeRequest>; analyze(request: CreativeRequest): unknown; select(request: CreativeRequest): unknown; preview(request: CreativeRequest): Promise<unknown>; render(request: CreativeRequest): Promise<unknown>; variants(request: CreativeRequest): unknown; validate(request: CreativeRequest): unknown; getProductCreatives(workspaceId: string, productId: string): Promise<unknown> }
export function registerCreativeStudioTools(registry: ToolRegistry, service: CreativeStudioToolService, workspaceId: string): void { const parameters = z.object({ productId: z.string().min(1), contentId: z.string().min(1), platform: z.enum(["pinterest", "facebook"]), format: z.enum(["PINTEREST_2_3", "FACEBOOK_4_5", "FACEBOOK_1_1"]), template: z.enum(["MINIMAL_OVERLAY", "BOTTOM_INFO_PANEL", "TOP_HEADLINE", "SIDE_INFO", "PHOTO_FIRST"]).default("PHOTO_FIRST"), variantCount: z.number().int().min(1).max(3).default(1) }); const load = async (input: z.infer<typeof parameters>) => service.request(workspaceId, input.productId, { contentId: input.contentId, platform: input.platform, format: input.format, template: input.template, variantCount: input.variantCount }); registry.register({ name: "analyze_product_images", description: "Analisa imagens reais com score explicável.", parameters, externalAction: false, execute: async input => service.analyze(await load(input)) }); registry.register({ name: "select_best_product_image", description: "Seleciona deterministicamente a melhor imagem real.", parameters, externalAction: false, execute: async input => service.select(await load(input)) }); registry.register({ name: "create_creative_preview", description: "Compõe preview local; não publica.", parameters, externalAction: false, execute: async input => service.preview(await load(input)) }); registry.register({ name: "render_product_creative", description: "Renderiza e persiste CreativeAsset sem publicar.", parameters, externalAction: false, execute: async input => service.render(await load(input)) }); registry.register({ name: "create_creative_variants", description: "Cria variações com objetivos editoriais distintos.", parameters, externalAction: false, execute: async input => service.variants(await load(input)) }); registry.register({ name: "validate_creative", description: "Valida imagem, preço, claims, crop, contraste e overlays.", parameters, externalAction: false, execute: async input => service.validate(await load(input)) }); registry.register({ name: "get_product_creatives", description: "Lista CreativeAssets persistidos do produto.", parameters: z.object({ productId: z.string().min(1) }), externalAction: false, execute: ({ productId }) => service.getProductCreatives(workspaceId, productId) }); }

export interface ContentOperationsToolService { run(date: Date): Promise<unknown>; listQueue(): Promise<unknown>; approve(id: string, actorId: string): Promise<unknown>; reject(id: string, actorId: string, reason: string): Promise<unknown>; approveBatch(ids: readonly string[], actorId: string): Promise<unknown>; schedule(id: string, actorId: string, at: Date): Promise<unknown>; publishNow(id: string, actorId: string): Promise<unknown>; cancel(id: string, actorId: string): Promise<unknown>; retry(id: string, actorId: string): Promise<unknown>; status(id: string): Promise<unknown>; alerts(): Promise<unknown> }
export function registerContentOperationsTools(registry: ToolRegistry, service: ContentOperationsToolService): void { const id = z.object({ id: z.string().min(1), actorId: z.string().min(1) }); registry.register({ name: "run_daily_operations", description: "Prepara o plano e a fila do dia sem publicar.", parameters: z.object({ date: z.coerce.date() }), externalAction: false, execute: ({ date }) => service.run(date) }); registry.register({ name: "list_publication_queue", description: "Lista a fila de aprovação.", parameters: z.object({}), externalAction: false, execute: () => service.listQueue() }); registry.register({ name: "approve_publication_item", description: "Aprovação humana explícita.", parameters: id, externalAction: true, execute: ({ id, actorId }) => service.approve(id, actorId) }); registry.register({ name: "reject_publication_item", description: "Rejeição humana explícita.", parameters: id.extend({ reason: z.string().min(1) }), externalAction: true, execute: ({ id, actorId, reason }) => service.reject(id, actorId, reason) }); registry.register({ name: "approve_publication_batch", description: "Aprovação humana em lote.", parameters: z.object({ ids: z.array(z.string()).min(1), actorId: z.string() }), externalAction: true, execute: ({ ids, actorId }) => service.approveBatch(ids, actorId) }); registry.register({ name: "schedule_publication", description: "Agenda item aprovado.", parameters: id.extend({ scheduledAt: z.coerce.date() }), externalAction: true, execute: ({ id, actorId, scheduledAt }) => service.schedule(id, actorId, scheduledAt) }); registry.register({ name: "publish_now", description: "Publicação externa protegida por aprovação.", parameters: id, externalAction: true, execute: ({ id, actorId }) => service.publishNow(id, actorId) }); registry.register({ name: "cancel_publication", description: "Cancela item publicável.", parameters: id, externalAction: true, execute: ({ id, actorId }) => service.cancel(id, actorId) }); registry.register({ name: "retry_publication", description: "Retry controlado e idempotente.", parameters: id, externalAction: true, execute: ({ id, actorId }) => service.retry(id, actorId) }); registry.register({ name: "get_publication_status", description: "Consulta status real persistido.", parameters: z.object({ id: z.string() }), externalAction: false, execute: ({ id }) => service.status(id) }); registry.register({ name: "list_operational_alerts", description: "Lista alertas operacionais.", parameters: z.object({}), externalAction: false, execute: () => service.alerts() }); }
