import { describe, expect, it, vi } from "vitest";
import type { HttpClient } from "../base/provider.js";
import { MercadoLivreDiscoverySource } from "./discovery-source.js";
import { MercadoLivreProductProvider } from "./product-provider.js";
describe("Mercado Livre discovery",()=>{
  it("normaliza trends e o envelope atual de highlights sem inventar ranking",async()=>{const request=vi.fn().mockResolvedValueOnce([{keyword:"organizador",url:"trend-url"}]).mockResolvedValueOnce([{keyword:"cozinha"}]).mockResolvedValueOnce({content:[{id:"MLB2",type:"ITEM",position:2},{id:"MLB1",type:"ITEM",position:1},{id:"MLBU1",type:"PRODUCT",position:3}]}),source=new MercadoLivreDiscoverySource({request} as HttpClient,async()=>"token");const result=await source.discover(["MLB1574"]);expect(result).toEqual(expect.arrayContaining([expect.objectContaining({term:"organizador",trendPosition:1}),expect.objectContaining({term:"mais vendidos",highlightPosition:1,highlightedItemIds:["MLB1","MLB2"]})]));expect(request).toHaveBeenCalledTimes(3)});
  it("resolve categorias reais pelo preditor oficial",async()=>{const request=vi.fn().mockResolvedValue([{category_id:"MLB123"}]),source=new MercadoLivreDiscoverySource({request} as HttpClient,async()=>"token");await expect(source.resolveCategories(["produtos para cozinha"])).resolves.toEqual({"produtos para cozinha":"MLB123"});expect(request.mock.calls[0]?.[0].url).toContain("/sites/MLB/domain_discovery/search?limit=1&q=produtos%20para%20cozinha")});
  it("usa somente os endpoints bulk atuais",async()=>{const request=vi.fn().mockResolvedValueOnce([{code:200,body:{id:"MLB1",title:"Produto",permalink:"https://example.com/p",available_quantity:5}}]).mockResolvedValueOnce([{code:200,body:{id:1,nickname:"Loja",seller_reputation:{level_id:"5_green"}}}]),provider=new MercadoLivreProductProvider({request} as HttpClient,async()=>"token");const [product]=await provider.getProducts(["MLB1"]),[seller]=await provider.getSellers(["1"]);expect(product?.salesCount).toBeNull();expect(seller?.reputation).toBe(100);expect(request.mock.calls.map(call=>call[0].url)).toEqual(["https://api.mercadolibre.com/items/bulk?ids=MLB1","https://api.mercadolibre.com/users/bulk?ids=1"])});
});
