import type { HttpClient } from "../base/provider.js";
import type { MarketplaceCategory, MarketplaceProduct, MarketplaceProductProvider, MarketplaceSeller, ProductSearchRequest } from "../marketplace/provider.js";
type SearchItem = { id?: string; title?: string; price?: number; currency_id?: string; permalink?: string; category_id?: string; sold_quantity?: number; available_quantity?: number; thumbnail?: string; tags?: string[]; official_store_id?: number; shipping?: { free_shipping?: boolean }; seller?: { id?: number; nickname?: string; seller_reputation?: { level_id?: string; power_seller_status?: string } }; reviews?: { rating_average?: number; total?: number } };
type Item = SearchItem & { description?: string; status?: string; pictures?: Array<{ secure_url?: string; url?: string }> };
type User = { id?: number; nickname?: string; seller_reputation?: { level_id?: string } };
const reputation: Readonly<Record<string, number>> = { "1_red": 20, "2_orange": 40, "3_yellow": 60, "4_light_green": 80, "5_green": 100 };
export class MercadoLivreProductProvider implements MarketplaceProductProvider {
  readonly marketplace = "mercadolivre"; readonly #baseUrl = "https://api.mercadolibre.com";
  constructor(private readonly http: HttpClient, private readonly accessToken: () => Promise<string>, private readonly siteId = "MLB") {}
  async searchProducts(request: ProductSearchRequest) { const query = new URLSearchParams({ q: request.query, limit: String(Math.min(request.limit, 50)), ...(request.categoryExternalId ? { category: request.categoryExternalId } : {}) }); const response = await this.get<{ results?: SearchItem[] }>(`/sites/${this.siteId}/search?${query}`); return (response.results ?? []).map(item => this.normalize(item)); }
  async getProduct(externalId: string) { try { return this.normalize(await this.get<Item>(`/items/${encodeURIComponent(externalId)}`)); } catch (error) { if (error instanceof Error && error.message === "provider_http_404") return null; throw error; } }
  async getSeller(externalId: string): Promise<MarketplaceSeller | null> { try { const value = await this.get<User>(`/users/${encodeURIComponent(externalId)}`); return { externalId, name: value.nickname ?? null, reputation: value.seller_reputation?.level_id ? reputation[value.seller_reputation.level_id] ?? null : null, rawSourceReference: `mercadolivre:user:${externalId}` }; } catch (error) { if (error instanceof Error && error.message === "provider_http_404") return null; throw error; } }
  async getCategories(): Promise<readonly MarketplaceCategory[]> { const values = await this.get<Array<{ id: string; name: string }>>(`/sites/${this.siteId}/categories`); return values.map(value => ({ externalId: value.id, name: value.name, parentExternalId: null })); }
  refreshProductData(externalId: string) { return this.getProduct(externalId); }
  private async get<T>(path: string) { const token = await this.accessToken(); return this.http.request<T>({ url: `${this.#baseUrl}${path}`, method: "GET", headers: { Authorization: `Bearer ${token}` } }); }
  private normalize(item: Item): MarketplaceProduct { const images = (item.pictures ?? []).map(value => value.secure_url ?? value.url).filter((value): value is string => Boolean(value)); if (images.length === 0 && item.thumbnail) images.push(item.thumbnail); const fields = { description: item.description, price: item.price, currency: item.currency_id, category: item.category_id, rating: item.reviews?.rating_average, reviewCount: item.reviews?.total, salesCount: item.sold_quantity, seller: item.seller?.id, sellerReputation: item.seller?.seller_reputation?.level_id, images: images.length ? images : undefined, availability: item.status ?? (item.available_quantity === undefined ? undefined : item.available_quantity > 0 ? "available" : "unavailable"), commission: undefined }; const missingFields = Object.entries(fields).filter(([, value]) => value === undefined || value === null).map(([key]) => key); const tags = item.tags ?? []; return { externalId: item.id ?? "", name: item.title ?? "", description: item.description ?? null, canonicalUrl: item.permalink ?? "", price: item.price ?? null, currency: item.currency_id ?? null, categoryExternalId: item.category_id ?? null, rating: item.reviews?.rating_average ?? null, reviewCount: item.reviews?.total ?? null, salesCount: item.sold_quantity ?? null, sellerExternalId: item.seller?.id === undefined ? null : String(item.seller.id), sellerName: item.seller?.nickname ?? null, sellerReputation: item.seller?.seller_reputation?.level_id ? reputation[item.seller.seller_reputation.level_id] ?? null : null, images, availability: fields.availability ?? null, commission: null, freeShipping: item.shipping?.free_shipping ?? null, isBestSeller: tags.includes("best_seller_candidate") || tags.includes("best_seller"), isMercadoLider: item.seller?.seller_reputation?.power_seller_status ? true : null, isOfficialStore: item.official_store_id === undefined ? null : item.official_store_id > 0, missingFields, rawSourceReference: `mercadolivre:item:${item.id ?? "unknown"}` }; }
}
