"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { hasAnalyticsData, integrationMessage, type QueueSummary } from "../dashboard-model";
import { InternalNav } from "../internal-nav";

const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001";
type Snapshot = { products: { awaitingReview: number; approved: number; opportunities: number | null; recentlyRejected: number }; queue: QueueSummary; creatives: { id: string; platform: string | null; status: string; previewUrl: string | null; createdAt: string }[] };
type Ready = { status: "ready" | "degraded" | "not_ready"; database: string; redis: string; worker: string; integrations: Record<string, string>; externalPublishing?: string };
type Integration = { provider: string; status: string; scopes?: string[]; capabilities?: Record<string, { available: boolean }> };
type Daily = { dataCoverage: number; topProducts: { id: string }[]; promisingProducts: { id: string }[]; weakProducts: { id: string }[]; message?: string | null };
type Overview = { kpis: Record<string, { value: number | null; availability: string }> };
type DailySummary = { prepared: number; blocked: number; skipped: number; needsReview: number };
type Alert = { id: string; type: string; message: string; createdAt: string };

async function json<T>(path: string, acceptErrorStatus = false): Promise<T> { const response = await fetch(`${api}${path}`, { cache: "no-store" }); if (!response.ok && !acceptErrorStatus) throw new Error(path); return response.json() as Promise<T>; }

export default function DashboardPage() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null), [ready, setReady] = useState<Ready | null>(null), [apiOk, setApiOk] = useState<boolean | null>(null), [integrations, setIntegrations] = useState<Integration[]>([]), [analytics, setAnalytics] = useState<Daily | null>(null), [overview, setOverview] = useState<Overview | null>(null), [alerts, setAlerts] = useState<Alert[]>([]), [daily, setDaily] = useState<DailySummary | null>(null), [working, setWorking] = useState(false);
  const load = useCallback(async () => {
    const now = new Date(), from = new Date(now.getTime() - 7 * 86_400_000), period = `?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(now.toISOString())}`;
    const [healthResult, readyResult, snapshotResult, integrationsResult, analyticsResult, overviewResult, alertsResult] = await Promise.allSettled([json<{status:string}>("/health"), json<Ready>("/ready", true), json<Snapshot>("/api/dashboard"), json<Integration[]>("/api/integrations"), json<Daily>(`/api/analytics/daily-summary${period}`), json<Overview>(`/api/analytics/overview${period}`), json<Alert[]>("/api/operations/alerts")]);
    setApiOk(healthResult.status === "fulfilled" && healthResult.value.status === "ok");
    if (readyResult.status === "fulfilled") setReady(readyResult.value);
    if (snapshotResult.status === "fulfilled") setSnapshot(snapshotResult.value);
    if (integrationsResult.status === "fulfilled") setIntegrations(integrationsResult.value);
    if (analyticsResult.status === "fulfilled") setAnalytics(analyticsResult.value);
    if (overviewResult.status === "fulfilled") setOverview(overviewResult.value);
    if (alertsResult.status === "fulfilled") setAlerts(alertsResult.value.slice(0, 5));
  }, []);
  useEffect(() => { void load(); }, [load]);
  const workToday = async () => { setWorking(true); try { const response = await fetch(`${api}/api/operations/daily/run`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ date: new Date().toISOString() }) }); if (response.ok) { const value = await response.json() as { summary?: DailySummary }; setDaily(value.summary ?? value as DailySummary); await load(); } } finally { setWorking(false); } };
  const dep = (label: string, value: string | boolean | null | undefined) => <div className="status-row"><span>{label}</span><strong className={`state state-${String(value)}`}>{value === null || value === undefined ? "Desconhecido" : value === true ? "Disponível" : value === false ? "Indisponível" : String(value).replaceAll("_", " ")}</strong></div>;
  return <div className="internal-shell"><InternalNav /><main className="dashboard-main">
    <header className="dashboard-welcome"><div><span className="dashboard-kicker">Visão de hoje</span><h1>Olá. Vamos cuidar da operação?</h1><p>Um resumo simples do que está funcionando e do que precisa da sua atenção.</p></div><button type="button" onClick={workToday} disabled={working}>{working ? "Preparando o dia…" : "Trabalhe o dia de hoje"}</button></header>
    <section className="dashboard-panel dashboard-status" aria-labelledby="status-title"><div className="panel-heading"><div><span className="dashboard-kicker">Ambiente</span><h2 id="status-title">Status do sistema</h2></div><span className={`readiness readiness-${ready?.status ?? "unknown"}`}>{ready?.status?.replace("_", " ") ?? "verificando"}</span></div><div className="status-grid">{dep("API", apiOk)}{dep("PostgreSQL", ready?.database)}{dep("Redis", ready?.redis)}{dep("Worker", ready?.worker)}{dep("Pinterest", ready?.integrations?.pinterest)}{dep("Publicação externa", ready?.externalPublishing ?? "disabled")}</div></section>
    <section className="dashboard-panel"><div className="panel-heading"><div><span className="dashboard-kicker">Ação assistida</span><h2>Trabalhe o dia de hoje</h2></div><Link href="/operations">Abrir operações →</Link></div>{daily ? <div className="metric-grid">{Object.entries(daily).map(([name,value]) => <div className="metric" key={name}><strong>{value}</strong><span>{name}</span></div>)}</div> : <p className="friendly-empty">Execute a preparação quando quiser. Nada será publicado automaticamente.</p>}</section>
    <div className="dashboard-columns"><section className="dashboard-panel" id="produtos"><div className="panel-heading"><h2>Produtos</h2></div>{snapshot ? <>{snapshot.products.awaitingReview === 0 && <p className="friendly-empty">Sem produtos aguardando revisão</p>}<div className="metric-list"><div><strong>{snapshot.products.awaitingReview}</strong><span>Aguardando revisão</span></div><div><strong>{snapshot.products.approved}</strong><span>Aprovados</span></div><div><strong>{snapshot.products.opportunities ?? "—"}</strong><span>{snapshot.products.opportunities === null ? "Oportunidades não apuradas" : "Oportunidades"}</span></div><div><strong>{snapshot.products.recentlyRejected}</strong><span>Rejeitados recentes</span></div></div></> : <p className="friendly-empty">Carregando produtos…</p>}</section>
      <section className="dashboard-panel"><div className="panel-heading"><h2>Fila</h2><Link href="/operations">Revisar fila →</Link></div>{snapshot ? <div className="metric-list">{Object.entries(snapshot.queue).map(([status,total]) => <div key={status}><strong>{total}</strong><span>{status.replaceAll("_", " ")}</span></div>)}</div> : <p className="friendly-empty">A fila ainda não está disponível.</p>}</section></div>
    <section className="dashboard-panel"><div className="panel-heading"><h2>Criativos recentes</h2><Link href="/creative-studio">Abrir Creative Studio →</Link></div>{snapshot?.creatives.length ? <div className="creative-grid">{snapshot.creatives.map((creative) => <article key={creative.id}>{creative.previewUrl ? <img src={creative.previewUrl} alt="Preview do criativo" /> : <div className="creative-placeholder">Preview indisponível</div>}<div><strong>{creative.platform ?? "Plataforma não informada"}</strong><span>{creative.status}</span></div></article>)}</div> : <p className="friendly-empty">Nenhum CreativeAsset disponível ainda.</p>}</section>
    <section className="dashboard-panel"><div className="panel-heading"><h2>Analytics</h2><Link href="/analytics">Ver análise completa →</Link></div>{hasAnalyticsData(analytics) ? <><div className="metric-grid"><div className="metric"><strong>{Math.round(analytics.dataCoverage * 100)}%</strong><span>Cobertura</span></div><div className="metric"><strong>{analytics.topProducts.length}</strong><span>Top products</span></div><div className="metric"><strong>{analytics.promisingProducts.length}</strong><span>Promising</span></div><div className="metric"><strong>{analytics.weakProducts.length}</strong><span>Weak</span></div>{Object.entries(overview?.kpis ?? {}).filter(([,kpi]) => kpi.value !== null && ["available", "zero"].includes(kpi.availability)).slice(0, 4).map(([name,kpi]) => <div className="metric" key={name}><strong>{kpi.value!.toFixed(4)}</strong><span>{name}</span></div>)}</div></> : <p className="friendly-empty">Dados insuficientes</p>}</section>
    <div className="dashboard-columns"><section className="dashboard-panel"><div className="panel-heading"><h2>Integrações</h2><Link href="/integrations">Configurar →</Link></div>{integrations.length ? integrations.map((item) => <article className="integration-row" key={item.provider}><div><strong>{item.provider === "facebook" ? "Meta" : item.provider === "mercadolivre" ? "Mercado Livre" : "Pinterest"}</strong><span>{integrationMessage(item.provider,item.status)}</span></div><small>{item.scopes?.length ? `${item.scopes.length} permissões concedidas` : "Sem permissões concedidas"} · {Object.values(item.capabilities ?? {}).filter((cap) => cap.available).length} recursos disponíveis</small></article>) : <p className="friendly-empty">Pinterest ainda não conectado</p>}</section>
      <section className="dashboard-panel"><div className="panel-heading"><h2>Alertas</h2></div>{alerts.length ? alerts.map((alert) => <article className="alert-row" key={alert.id}><strong>{alert.type.replaceAll("_", " ")}</strong><p>{alert.message}</p></article>) : <p className="friendly-empty">Nenhum alerta operacional recente.</p>}</section></div>
  </main></div>;
}
