import { describe, expect, it, vi } from "vitest";
import type { HttpClient } from "./base/provider.js";
import { createMetaProvider } from "./meta/index.js";
import { MercadoLivreProductProvider } from "./mercadolivre/product-provider.js";

describe("integration compatibility",()=>{
  it("keeps Mercado Livre unit endpoints and normalizes official signals without inventing fields",async()=>{const request=vi.fn().mockResolvedValueOnce({results:[{id:"MLB1",title:"Organizador",price:79.9,currency_id:"BRL",permalink:"https://produto.mercadolivre.com.br/MLB1",category_id:"MLB1",available_quantity:1,thumbnail:"https://http2.mlstatic.com/image.jpg",tags:["best_seller"],official_store_id:12,seller:{seller_reputation:{level_id:"5_green",power_seller_status:"gold"}}}]}).mockResolvedValueOnce({id:123,nickname:"Loja",seller_reputation:{level_id:"4_light_green"}});const provider=new MercadoLivreProductProvider({request}as HttpClient,async()=>"token");const [product]=await provider.searchProducts({query:"organizador",limit:20});expect(product).toMatchObject({rating:null,sellerReputation:100,isBestSeller:true,isMercadoLider:true,isOfficialStore:true});expect(product?.missingFields).toContain("rating");expect(await provider.getSeller("123")).toMatchObject({name:"Loja",reputation:80});const urls=request.mock.calls.map(call=>String(call[0].url));expect(urls).not.toContain(expect.stringContaining("/items?ids="));expect(urls).not.toContain(expect.stringContaining("/users?ids="));expect(urls[1]).toBe("https://api.mercadolibre.com/users/123")});
  it("keeps Meta capabilities separate and create_comment unavailable",async()=>{const request=vi.fn().mockResolvedValue({id:"user"});const provider=createMetaProvider("id","secret","v23.0",{request});const capabilities=await provider.getCapabilities("token",["pages_show_list","pages_read_engagement","pages_manage_posts"]);expect(capabilities.list_pages?.available).toBe(true);expect(capabilities.read_page?.available).toBe(true);expect(capabilities.create_page_post).toMatchObject({available:false,reason:"feature_disabled"});expect(capabilities.create_comment).toMatchObject({available:false,reason:"provider_unsupported"})});
});
