import {spawn} from "node:child_process";
import {createServer} from "node:net";

const targets=[{name:"Web",port:3000,url:"http://127.0.0.1:3000/"},{name:"API",port:3001,url:"http://127.0.0.1:3001/health"}];
const checkOnly=process.argv.includes("--check-only");
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const portAvailable=port=>new Promise(resolve=>{const server=createServer();server.unref();server.once("error",()=>resolve(false));server.listen({host:"127.0.0.1",port,exclusive:true},()=>server.close(()=>resolve(true)))});
async function preflight(){for(const target of targets)if(!await portAvailable(target.port))throw new Error(`${target.name} não iniciou: a porta ${target.port} já está ocupada. Encerre o processo duplicado e tente novamente.`)}
async function responseOk(url){try{return(await fetch(url,{signal:AbortSignal.timeout(1500)})).status===200}catch{return false}}
async function checkRunning(){const results=await Promise.all(targets.map(async target=>({...target,ok:await responseOk(target.url)})));const assisted=await responseOk("http://127.0.0.1:3001/api/assisted-publication/products");for(const result of results)console.log(`${result.ok?"✓":"✗"} ${result.name}: ${result.url}`);console.log(`${assisted?"✓":"✗"} Modo assistido: http://127.0.0.1:3001/api/assisted-publication/products`);if(results.some(result=>!result.ok)||!assisted)process.exitCode=1}
if(checkOnly){await checkRunning()}else{try{await preflight()}catch(error){console.error(error instanceof Error?error.message:String(error));process.exit(1)}const pnpm=process.env.npm_execpath;if(!pnpm){console.error("Não foi possível localizar o pnpm usado para iniciar o projeto.");process.exit(1)}const child=spawn(process.execPath,[pnpm,"exec","turbo","run","dev"],{cwd:process.cwd(),env:process.env,stdio:["inherit","pipe","pipe"],detached:process.platform!=="win32"});const terminate=()=>{if(!child.pid||child.exitCode!==null)return;if(process.platform==="win32")spawn("taskkill",["/pid",String(child.pid),"/T","/F"],{stdio:"ignore"});else process.kill(-child.pid,"SIGTERM")};let workerReady=false,settled=false;const mirror=(stream,output)=>{stream.setEncoding("utf8");stream.on("data",chunk=>{output.write(chunk);if(chunk.includes("Worker started"))workerReady=true})};mirror(child.stdout,process.stdout);mirror(child.stderr,process.stderr);child.once("exit",code=>{if(!settled&&code!==0)console.error(`Ambiente de desenvolvimento encerrou antes de ficar pronto (código ${code??"desconhecido"}).`);process.exitCode=code??1});for(const signal of ["SIGINT","SIGTERM"])process.once(signal,terminate);const deadline=Date.now()+60_000;let web=false,api=false,assisted=false;while(Date.now()<deadline&&!settled){if(child.exitCode!==null)break;[web,api,assisted]=await Promise.all([responseOk(targets[0].url),responseOk(targets[1].url),responseOk("http://127.0.0.1:3001/api/assisted-publication/products")]);if(web&&api&&assisted&&workerReady){settled=true;console.log("\n✓ CasaPrática pronto: Web 3000, API 3001, Modo Assistido e Worker ativos.\n");break}await wait(500)}if(!settled&&child.exitCode===null){console.error(`Falha ao iniciar: Web=${web}, API=${api}, Assisted=${assisted}, Worker=${workerReady}. Consulte os erros acima.`);terminate();process.exitCode=1}}
