import { Prisma, type PrismaClient } from "@prisma/client";
import { normalizedMetricSchema, type AnalyticsFilter, type AnalyticsPeriod, type NormalizedMetric } from "@casapratica/domain";
import type { AnalyticsRepository, StoredMetric } from "@casapratica/strategy";

const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const record = (value: Prisma.JsonValue | null): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
export class PrismaAnalyticsRepository implements AnalyticsRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async appendMetrics(workspaceId: string, metrics: readonly NormalizedMetric[]) { await this.prisma.$transaction(metrics.map(metric => this.prisma.metricSnapshot.create({ data: { workspaceId, publicationId: metric.publicationId, productId: metric.productId, source: metric.source, observedAt: metric.capturedAt, impressions: metric.metricName === "impressions" ? metric.value : null, clicks: ["clicks", "pinClicks", "outboundClicks", "affiliateClicks"].includes(metric.metricName) ? metric.value : null, saves: metric.metricName === "saves" ? metric.value : null, conversions: metric.metricName === "conversions" ? metric.value : null, revenue: metric.metricName === "revenue" ? metric.value : null, currency: typeof metric.metadata.currency === "string" ? metric.metadata.currency : null, rawData: json(metric) } }))); return metrics.length; }
  async listMetrics(workspaceId: string, period: AnalyticsPeriod, filter: AnalyticsFilter = {}) { const rows = await this.prisma.metricSnapshot.findMany({ where: { workspaceId, observedAt: { gte: period.start, lte: period.end }, ...(filter.productId ? { productId: filter.productId } : {}), ...(filter.publicationId ? { publicationId: filter.publicationId } : {}), ...(filter.platform || filter.categoryId || filter.creativeAssetId ? { publication: { ...(filter.platform ? { channel: filter.platform } : {}), ...(filter.creativeAssetId ? { creativeAssetId: filter.creativeAssetId } : {}), ...(filter.categoryId ? { product: { categoryId: filter.categoryId } } : {}) } } : {}) }, orderBy: { observedAt: "asc" } }); return rows.flatMap<StoredMetric>(row => { const data = record(row.rawData); const parsed = normalizedMetricSchema.safeParse(data); if (parsed.success) return [{ id: row.id, ...parsed.data, createdAt: row.createdAt }]; const legacy = [["impressions", row.impressions], ["clicks", row.clicks], ["saves", row.saves], ["conversions", row.conversions], ["revenue", row.revenue?.toNumber() ?? null]] as const; return legacy.filter((entry): entry is readonly [typeof entry[0], number] => entry[1] !== null).map(([metricName, value]) => ({ id: `${row.id}:${metricName}`, platform: row.source === "pinterest" ? "pinterest" as const : row.source === "facebook" || row.source === "meta" ? "facebook" as const : "business" as const, source: row.source === "pinterest" || row.source === "meta" || row.source === "affiliate" || row.source === "manual" ? row.source : "imported" as const, metricName, value, capturedAt: row.observedAt, periodStart: row.observedAt, periodEnd: row.observedAt, externalEntityId: null, publicationId: row.publicationId, productId: row.productId, contentId: null, categoryId: null, availability: value === 0 ? "zero" as const : "available" as const, confidence: .5, metadata: { legacySnapshot: true }, normalizedAt: row.createdAt, createdAt: row.createdAt })); }); }
  async listConversions(workspaceId: string, period: AnalyticsPeriod, filter: AnalyticsFilter = {}) { const rows = await this.prisma.conversion.findMany({ where: { workspaceId, occurredAt: { gte: period.start, lte: period.end }, ...(filter.productId ? { productId: filter.productId } : {}), ...(filter.publicationId ? { publicationId: filter.publicationId } : {}), ...(filter.platform || filter.categoryId || filter.creativeAssetId ? { publication: { ...(filter.platform ? { channel: filter.platform } : {}), ...(filter.creativeAssetId ? { creativeAssetId: filter.creativeAssetId } : {}), ...(filter.categoryId ? { product: { categoryId: filter.categoryId } } : {}) } } : {}) }, orderBy: { occurredAt: "asc" } }); return rows.map(row => ({ id: row.id, source: row.source, publicationId: row.publicationId, productId: row.productId, occurredAt: row.occurredAt, amount: row.amount?.toNumber() ?? null, commission: row.commission?.toNumber() ?? null, currency: row.currency })); }
  async listExperiments(workspaceId: string, period: AnalyticsPeriod) { const rows = await this.prisma.experiment.findMany({ where: { workspaceId, OR: [{ startsAt: null }, { startsAt: { lte: period.end } }], AND: [{ OR: [{ endsAt: null }, { endsAt: { gte: period.start } }] }] }, orderBy: { createdAt: "desc" } }); return rows.map(row => ({ id: row.id, name: row.name, hypothesis: row.hypothesis, status: row.status, startsAt: row.startsAt, endsAt: row.endsAt, configuration: record(row.configuration), result: row.result ? record(row.result) : null })); }
}
