import { randomUUID } from "node:crypto";
import { Prisma, type PrismaClient } from "@prisma/client";

const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const slug = (value: string) => value.toLocaleLowerCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "sem-categoria";

export type ManualProductInput = { productUrl:string; affiliateUrl?:string|null|undefined; name:string; category:string; price?:number|null|undefined; rating?:number|null|undefined; reviewCount?:number|null|undefined; seller?:string|null|undefined; imageUrl?:string|null|undefined; confirmedFacts?:string|null|undefined };
export type AssistedPackInput = { productId:string; platform:"pinterest"|"facebook"; image:string|null; title:string|null; body:string; destinationUrl:string; affiliateUrl:string|null; boardSuggestion:string|null; keywords:readonly string[]; manualSteps:readonly string[]; contentFingerprint:string };

export class PrismaAssistedPublicationRepository {
  constructor(private readonly db: PrismaClient) {}
  async listProducts(workspaceId:string) { const rows=await this.db.product.findMany({where:{workspaceId,status:{in:["approved","test"]}},include:{category:true,seller:true,scores:{orderBy:{calculatedAt:"desc"},take:1}},orderBy:[{status:"asc"},{updatedAt:"desc"}]}); return rows.map(p=>({id:p.id,name:p.name,image:p.thumbnailUrl,category:p.category?.name??null,price:p.price===null?null:Number(p.price),currency:p.currency,rating:p.rating===null?null:Number(p.rating),reviewCount:p.reviewCount,seller:p.seller?.name??null,score:p.scores[0]?Number(p.scores[0].score):null,confidence:p.scores[0]?Number(p.scores[0].confidence):null,status:p.status,source:p.marketplace==="MANUAL_INPUT"?"MANUAL_INPUT":"PERSISTED"})); }
  async createManualProduct(workspaceId:string,input:ManualProductInput) { return this.db.$transaction(async tx=>{const category=await tx.category.upsert({where:{workspaceId_slug:{workspaceId,slug:slug(input.category)}},update:{name:input.category},create:{workspaceId,name:input.category,slug:slug(input.category)}});let sellerId:string|undefined;if(input.seller){const seller=await tx.seller.upsert({where:{workspaceId_marketplace_externalId:{workspaceId,marketplace:"MANUAL_INPUT",externalId:slug(input.seller)}},update:{name:input.seller},create:{workspaceId,marketplace:"MANUAL_INPUT",externalId:slug(input.seller),name:input.seller}});sellerId=seller.id}const product=await tx.product.create({data:{workspaceId,marketplace:"MANUAL_INPUT",externalId:`manual-${randomUUID()}`,name:input.name,description:input.confirmedFacts??null,categoryId:category.id,canonicalUrl:input.productUrl,affiliateUrl:input.affiliateUrl??null,price:input.price??null,currency:input.price===null||input.price===undefined?null:"BRL",rating:input.rating??null,reviewCount:input.reviewCount??null,sellerId:sellerId??null,thumbnailUrl:input.imageUrl??null,status:"test",firstSeenAt:new Date()}});await tx.auditLog.create({data:{workspaceId,actorType:"owner",action:"product.manual_input",resourceType:"Product",resourceId:product.id,metadata:json({source:"MANUAL_INPUT",limitedConfidence:true})}});return {id:product.id,status:product.status,source:"MANUAL_INPUT" as const,limitedConfidence:true};}); }
  async product(workspaceId:string,id:string) { const p=await this.db.product.findFirst({where:{workspaceId,id,status:{in:["approved","test"]}},include:{affiliateLinks:{where:{active:true},orderBy:{updatedAt:"desc"},take:1},contents:{orderBy:{createdAt:"desc"},take:5,include:{creativeAssets:{where:{status:"ready"},orderBy:{createdAt:"desc"},take:1}}}}});if(!p)throw new Error("product_not_eligible");const asset=p.contents.flatMap(c=>c.creativeAssets)[0];const assetUrl=asset&&(/^(https?:\/\/|\/)/.test(asset.storageKey))?asset.storageKey:null;return{id:p.id,name:p.name,image:assetUrl??p.thumbnailUrl,destinationUrl:p.affiliateLinks[0]?.url??p.affiliateUrl??p.canonicalUrl,affiliateUrl:p.affiliateLinks[0]?.url??p.affiliateUrl??null}; }
  async savePack(workspaceId:string,input:AssistedPackInput) { return this.db.assistedPublicationPack.create({data:{workspaceId,...input,keywords:[...input.keywords],manualSteps:json(input.manualSteps)},include:{product:{select:{name:true}}}}); }
  async markPublished(workspaceId:string,id:string,actor:string,date:Date) { const found=await this.db.assistedPublicationPack.findFirst({where:{id,workspaceId}});if(!found)throw new Error("assisted_pack_not_found");const pack=await this.db.assistedPublicationPack.update({where:{id},data:{status:"MANUALLY_PUBLISHED",manuallyPublishedAt:date,manuallyPublishedBy:actor}});await this.db.auditLog.create({data:{workspaceId,actorType:"owner",actorId:actor,action:"publication.manual",resourceType:"AssistedPublicationPack",resourceId:id,metadata:json({platform:pack.platform,publicationMethod:"MANUAL",contentFingerprint:pack.contentFingerprint,externalId:null})}});return pack; }
  async history(workspaceId:string) { return this.db.assistedPublicationPack.findMany({where:{workspaceId,status:{in:["READY","MANUALLY_PUBLISHED"]}},include:{product:{select:{name:true}}},orderBy:{generatedAt:"desc"},take:30}); }
}
