import { Prisma, type PrismaClient } from "@prisma/client";
import type { ContentHistoryItem, ContentRepository, ContentVariantDraft, SavedContent } from "@casapratica/strategy";

const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const platform = (value: string): "pinterest" | "facebook" => value === "pinterest" ? "pinterest" : "facebook";
export class PrismaContentRepository implements ContentRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async getProductFacts(workspaceId: string, productId: string) { const value = await this.prisma.product.findFirst({ where: { id: productId, workspaceId }, include: { affiliateLinks: { where: { active: true }, orderBy: { updatedAt: "desc" }, take: 1 } } }); return value ? { id: value.id, workspaceId, name: value.name, description: value.description, affiliateUrl: value.affiliateLinks[0]?.url ?? value.affiliateUrl, rating: value.rating?.toNumber() ?? null, reviewCount: value.reviewCount, currentPrice: value.price?.toNumber() ?? null, priceCheckedAt: value.lastCheckedAt } : null; }
  async listProductContent(workspaceId: string, productId: string) { const values = await this.prisma.contentVariant.findMany({ where: { content: { workspaceId, productId } }, orderBy: { createdAt: "desc" } }); return values.map(value => this.map(value)); }
  async listRecentContent(workspaceId: string) { const since = new Date(Date.now() - 180 * 86_400_000); const values = await this.prisma.contentVariant.findMany({ where: { content: { workspaceId }, createdAt: { gte: since } }, orderBy: { createdAt: "desc" } }); return values.map(value => this.map(value)); }
  async create(workspaceId: string, productId: string | null, title: string, body: string, variants: readonly ContentVariantDraft[]): Promise<SavedContent> { return this.prisma.$transaction(async tx => { const content = await tx.content.create({ data: { workspaceId, productId, title, body, status: "draft", variants: { create: variants.map(value => ({ channel: value.platform, title: value.title, body: value.body, metadata: json(value.metadata) })) } }, include: { variants: true } }); return { id: content.id, productId: content.productId, status: "draft", variants: content.variants.map(value => this.map(value)) }; }); }
  async createVariant(workspaceId: string, contentId: string, variant: ContentVariantDraft) { const content = await this.prisma.content.findFirst({ where: { id: contentId, workspaceId } }); if (!content) throw new Error("content_not_found"); return this.map(await this.prisma.contentVariant.create({ data: { contentId, channel: variant.platform, title: variant.title, body: variant.body, metadata: json(variant.metadata) } })); }
  private map(value: { id: string; contentId: string; channel: string; title: string | null; body: string; metadata: Prisma.JsonValue; createdAt: Date }): ContentHistoryItem { const data = value.metadata && typeof value.metadata === "object" && !Array.isArray(value.metadata) ? value.metadata as Readonly<Record<string, unknown>> : {}; return { id: value.id, productId: null, platform: platform(value.channel), title: value.title, body: value.body, metadata: data, createdAt: value.createdAt }; }
}
