import { Prisma, type PrismaClient } from "@prisma/client";
import { creativeRequestSchema, type CreativeOutput, type CreativeRequest } from "@casapratica/domain";
import type { CreativeStudioRepository } from "@casapratica/strategy";
const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const record = (value: Prisma.JsonValue | null) => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
export class PrismaCreativeStudioRepository implements CreativeStudioRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async getRequest(workspaceId: string, productId: string, input: { contentId: string; platform: "pinterest" | "facebook"; format: CreativeRequest["format"]; template: CreativeRequest["template"]; variantCount: number }) { const product = await this.prisma.product.findFirst({ where: { id: productId, workspaceId }, include: { contents: { where: { id: input.contentId }, include: { creativeAssets: { where: { kind: "product_source" } } } } } }); if (!product) throw new Error("product_not_found"); const content = product.contents[0]; if (!content) throw new Error("content_not_found"); const images = content.creativeAssets.map(asset => { const data = record(asset.metadata); return { imageUrl: asset.storageKey, sourceUrl: String(data.sourceUrl ?? asset.storageKey), sourceProvider: String(data.sourceProvider ?? product.marketplace), externalProductId: product.externalId, imageHash: typeof data.imageHash === "string" ? data.imageHash : null, width: asset.width, height: asset.height, mimeType: asset.mimeType, capturedAt: asset.createdAt, assetSource: data.assetSource ?? "MARKETPLACE_PRODUCT_IMAGE", usageStatus: data.usageStatus ?? "UNKNOWN", hasConflictingText: data.hasConflictingText ?? false, productVisible: data.productVisible ?? true, focusScore: data.focusScore ?? .8, lightingScore: data.lightingScore ?? .8, visualNoiseScore: data.visualNoiseScore ?? .2, overlaySpaceScore: data.overlaySpaceScore ?? .5, usageDemonstration: data.usageDemonstration ?? false }; }).filter(image => image.width && image.height); const metadata = record((await this.prisma.contentVariant.findFirst({ where: { contentId: content.id, channel: input.platform }, orderBy: { createdAt: "desc" } }))?.metadata ?? null); return creativeRequestSchema.parse({ workspaceId, productId, ...input, productName: product.name, confirmedFacts: Array.isArray(metadata.productFacts) ? metadata.productFacts.slice(0, 2) : [], safeBenefits: [], price: product.price?.toNumber() ?? null, priceCheckedAt: product.lastCheckedAt, priceRequested: Boolean(metadata.priceDisplayRequested), images }); }
  async saveAsset(workspaceId: string, request: CreativeRequest, rendered: { storageKey: string; width: number; height: number; mimeType: string }, output: CreativeOutput) { await this.prisma.creativeAsset.create({ data: { workspaceId, contentId: request.contentId, kind: "composed_creative", storageKey: rendered.storageKey, mimeType: rendered.mimeType, width: rendered.width, height: rendered.height, status: output.status === "READY" ? "ready" : "draft", metadata: json(output.metadata) } }); return output; }
  async listAssets(workspaceId: string, productId: string) { return this.prisma.creativeAsset.findMany({ where: { workspaceId, kind: "composed_creative", content: { productId } }, orderBy: { createdAt: "desc" } }); }
}
