import { Prisma, type PrismaClient } from "@prisma/client";
import { facebookContentPillarSchema, weeklyFacebookStrategySchema, type ContentAngle, type FacebookCreativeBrief, type WeeklyFacebookStrategy } from "@casapratica/domain";
import type { FacebookContentCandidate, FacebookStrategyRepository } from "@casapratica/strategy";

const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const record = (value: Prisma.JsonValue | null): Readonly<Record<string, unknown>> => value && typeof value === "object" && !Array.isArray(value) ? value as Readonly<Record<string, unknown>> : {};
export class PrismaFacebookStrategyRepository implements FacebookStrategyRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async saveStrategy(workspaceId: string, strategy: WeeklyFacebookStrategy) { const latest = await this.prisma.strategy.findFirst({ where: { workspaceId, name: "facebook" }, orderBy: { version: "desc" } }); await this.prisma.$transaction([this.prisma.strategy.updateMany({ where: { workspaceId, name: "facebook", active: true }, data: { active: false } }), this.prisma.strategy.create({ data: { workspaceId, name: "facebook", version: (latest?.version ?? 0) + 1, active: true, configuration: json(strategy) } })]); return strategy; }
  async getStrategy(workspaceId: string) { const value = await this.prisma.strategy.findFirst({ where: { workspaceId, name: "facebook", active: true }, orderBy: { version: "desc" } }); return value ? weeklyFacebookStrategySchema.parse(value.configuration) : null; }
  async listFacebookContent(workspaceId: string) { const values = await this.prisma.contentVariant.findMany({ where: { channel: "facebook", content: { workspaceId, status: { in: ["draft", "ready"] } } }, include: { content: { include: { product: { include: { category: true, affiliateLinks: { where: { active: true }, orderBy: { updatedAt: "desc" }, take: 1 } } } } } }, orderBy: { createdAt: "desc" } }); return values.map(value => this.map(value)); }
  async getFacebookContent(workspaceId: string, contentOrProductId: string) { const value = await this.prisma.contentVariant.findFirst({ where: { channel: "facebook", content: { workspaceId }, OR: [{ contentId: contentOrProductId }, { content: { productId: contentOrProductId } }] }, include: { content: { include: { product: { include: { category: true, affiliateLinks: { where: { active: true }, orderBy: { updatedAt: "desc" }, take: 1 } } } } } }, orderBy: { createdAt: "desc" } }); return value ? this.map(value) : null; }
  async createPublicationPreparation(workspaceId: string, content: FacebookContentCandidate, brief: FacebookCreativeBrief, commentAction: "MANUAL_REQUIRED" | null) { const queue = await this.prisma.$transaction(async tx => { const created = await tx.publicationQueueItem.create({ data: { workspaceId, productId: content.productId, contentId: content.contentId, contentVariantId: content.variantId, channel: "facebook", status: "awaiting_approval" } }); await tx.auditLog.create({ data: { workspaceId, actorType: "system", action: "facebook.post_prepared", resourceType: "PublicationQueueItem", resourceId: created.id, metadata: json({ linkPlacement: content.linkPlacement, preparedComment: content.preparedComment, commentAction, creativeBrief: brief, approvalRequired: true, published: false }) } }); return created; }); return { queueItemId: queue.id, status: "approval_required" as const, commentAction }; }
  async getCapability(workspaceId: string, capability: "read_page" | "create_post") { const value = await this.prisma.integrationCapability.findFirst({ where: { capability, integrationAccount: { workspaceId, provider: "facebook", status: "connected" } } }); return { available: value?.status === "available", reason: value ? `status_${value.status}` : "not_connected_or_not_checked" }; }
  private map(value: { id: string; contentId: string; body: string; metadata: Prisma.JsonValue; createdAt: Date; content: { productId: string | null; product: null | { name: string; affiliateUrl: string | null; thumbnailUrl: string | null; price: Prisma.Decimal | null; lastCheckedAt: Date | null; category: { name: string } | null; affiliateLinks: readonly { url: string }[] } } }): FacebookContentCandidate { const data = record(value.metadata), product = value.content.product, affiliateUrl = product?.affiliateLinks[0]?.url ?? product?.affiliateUrl ?? null, rawComment = record((data.comment ?? null) as Prisma.JsonValue | null), pillar = facebookContentPillarSchema.catch("informational").parse(data.contentPillar); const preparedComment = affiliateUrl && data.linkPlacement === "COMMENT" ? { body: String(rawComment.body ?? "Confira informações, condições e preço atual no link:"), affiliateUrl, affiliateDisclosure: String(rawComment.affiliateDisclosure ?? "Este conteúdo contém link de afiliado; podemos receber comissão.") } : null; return { contentId: value.contentId, variantId: value.id, productId: value.content.productId, contentPillar: pillar, contentAngle: String(data.contentAngle ?? "utility") as ContentAngle, copy: value.body, cta: typeof data.cta === "string" ? data.cta : null, linkPlacement: data.linkPlacement === "BODY" || data.linkPlacement === "COMMENT" ? data.linkPlacement : "NONE", preparedComment, visualBrief: String(data.visualBrief ?? "Usar imagem real disponível em visual limpo."), affiliateUrl, productName: product?.name ?? null, category: product?.category?.name ?? null, images: product?.thumbnailUrl ? [product.thumbnailUrl] : [], currentPrice: product?.price?.toNumber() ?? null, priceCheckedAt: product?.lastCheckedAt ?? null, createdAt: value.createdAt }; }
}
