export * from "./prisma.js";
export * from "./session-repositories.js";
export * from "./integration-repositories.js";
export * from "./research-repository.js";
export * from "./content-repository.js";
export * from "./pinterest-strategy-repository.js";
export * from "./facebook-strategy-repository.js";
export * from "./creative-studio-repository.js";
export * from "./operations-repository.js";
export * from "./analytics-repository.js";
export * from "./dashboard-repository.js";
export * from "./product-review-repository.js";
export * from "./meta-page-repository.js";
export * from "./assisted-publication-repository.js";
export * from "./workspace-repository.js";
export * from "./product-import-repository.js";
export type DatabaseRepository = { readonly kind: "postgresql" };
