import { Prisma, type PrismaClient } from "@prisma/client";
import type { PinterestContentCandidate, PinterestStrategyRepository } from "@casapratica/strategy";
import { weeklyPinterestStrategySchema, type ContentAngle, type PinterestCreativeBrief, type WeeklyPinterestStrategy } from "@casapratica/domain";

const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const record = (value: Prisma.JsonValue | null): Readonly<Record<string, unknown>> => value && typeof value === "object" && !Array.isArray(value) ? value as Readonly<Record<string, unknown>> : {};
export class PrismaPinterestStrategyRepository implements PinterestStrategyRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async saveStrategy(workspaceId: string, strategy: WeeklyPinterestStrategy) { const latest = await this.prisma.strategy.findFirst({ where: { workspaceId, name: "pinterest" }, orderBy: { version: "desc" } }); await this.prisma.$transaction([this.prisma.strategy.updateMany({ where: { workspaceId, name: "pinterest", active: true }, data: { active: false } }), this.prisma.strategy.create({ data: { workspaceId, name: "pinterest", version: (latest?.version ?? 0) + 1, active: true, configuration: json(strategy) } })]); return strategy; }
  async getStrategy(workspaceId: string) { const value = await this.prisma.strategy.findFirst({ where: { workspaceId, name: "pinterest", active: true }, orderBy: { version: "desc" } }); return value ? weeklyPinterestStrategySchema.parse(value.configuration) : null; }
  async listPinterestContent(workspaceId: string) { const values = await this.prisma.contentVariant.findMany({
    where: { channel: "pinterest", content: { workspaceId, status: { in: ["draft", "ready"] } } },
    include: { content: { include: { product: { include: { category: true, affiliateLinks: { where: { active: true }, orderBy: { updatedAt: "desc" }, take: 1 } } } } } },
    orderBy: { createdAt: "desc" },
  }); return values.map(value => this.map(value)); }
  async getPinterestContent(workspaceId: string, contentOrProductId: string) { const value = await this.prisma.contentVariant.findFirst({
    where: { channel: "pinterest", content: { workspaceId }, OR: [{ contentId: contentOrProductId }, { content: { productId: contentOrProductId } }] },
    include: { content: { include: { product: { include: { category: true, affiliateLinks: { where: { active: true }, orderBy: { updatedAt: "desc" }, take: 1 } } } } } },
    orderBy: { createdAt: "desc" },
  }); return value ? this.map(value) : null; }
  async createPublicationPreparation(workspaceId: string, content: PinterestContentCandidate, board: string, brief: PinterestCreativeBrief) { const queue = await this.prisma.$transaction(async tx => { const created = await tx.publicationQueueItem.create({ data: { workspaceId, productId: content.productId, contentId: content.contentId, contentVariantId: content.variantId, channel: "pinterest", status: "awaiting_approval" } }); await tx.auditLog.create({ data: { workspaceId, actorType: "system", action: "pinterest.pin_prepared", resourceType: "PublicationQueueItem", resourceId: created.id, metadata: json({ boardSuggestion: board, creativeBrief: brief, approvalRequired: true, published: false }) } }); return created; }); return { queueItemId: queue.id, status: "approval_required" as const }; }
  async getCapability(workspaceId: string, capability: "read_boards" | "create_pin") { const value = await this.prisma.integrationCapability.findFirst({ where: { capability, integrationAccount: { workspaceId, provider: "pinterest", status: "connected" } }, orderBy: { checkedAt: "desc" } }); return { available: value?.status === "available", reason: value ? String(record(value.details).reason ?? value.status) : "integration_or_capability_not_found" }; }
  private map(value: { id: string; contentId: string; title: string | null; body: string; metadata: Prisma.JsonValue; createdAt: Date; content: { productId: string | null; product: null | { name: string; affiliateUrl: string | null; thumbnailUrl: string | null; price: Prisma.Decimal | null; lastCheckedAt: Date | null; category: { name: string } | null; affiliateLinks: readonly { url: string }[] } } }): PinterestContentCandidate { const data = record(value.metadata), product = value.content.product; return { contentId: value.contentId, variantId: value.id, productId: value.content.productId, title: value.title ?? String(data.title ?? "Pin CasaPrática"), description: value.body, cta: String(data.cta ?? "Confira os detalhes."), keywords: Array.isArray(data.keywords) ? data.keywords.filter((item): item is string => typeof item === "string") : [], keywordCluster: String(data.keywordCluster ?? "casa prática"), contentAngle: String(data.contentAngle ?? "utility") as ContentAngle, visualBrief: String(data.visualBrief ?? "Usar imagem real disponível."), boardSuggestion: String(data.boardSuggestion ?? "Utilidades para Casa"), affiliateUrl: product?.affiliateLinks[0]?.url ?? product?.affiliateUrl ?? null, productName: product?.name ?? null, category: product?.category?.name ?? null, images: product?.thumbnailUrl ? [product.thumbnailUrl] : [], currentPrice: product?.price?.toNumber() ?? null, priceCheckedAt: product?.lastCheckedAt ?? null, createdAt: value.createdAt }; }
}
