import { Prisma, type PrismaClient, type ProductStatus } from "@prisma/client";
import type { RankedCandidate, ResearchRepository, SavedResearchRun } from "@casapratica/strategy";
const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
export class PrismaResearchRepository implements ResearchRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async save(run: Omit<SavedResearchRun, "id">): Promise<SavedResearchRun> {
    const saved = await this.prisma.$transaction(async tx => {
      const research = await tx.productResearchRun.create({ data: { workspaceId: run.workspaceId, query: run.queries.join(" | "), queries: [...run.queries], categories: [...run.categories], provider: run.provider, candidateCount: run.candidates.length, recommendedCount: run.recommended, opportunityCount: run.opportunities, rejectedCount: run.rejected, reasons: json(run.reasons), durationMs: run.durationMs, status: "succeeded", startedAt: new Date(run.date.getTime() - run.durationMs), completedAt: run.date } });
      for (const [index, candidate] of run.candidates.entries()) {
        const value = candidate.product;
        const seller = value.sellerExternalId ? await tx.seller.upsert({ where: { workspaceId_marketplace_externalId: { workspaceId: run.workspaceId, marketplace: run.provider, externalId: value.sellerExternalId } }, create: { workspaceId: run.workspaceId, marketplace: run.provider, externalId: value.sellerExternalId, name: value.sellerName, reputation: value.sellerReputation }, update: { name: value.sellerName, reputation: value.sellerReputation } }) : null;
        const product = await tx.product.upsert({ where: { workspaceId_marketplace_externalId: { workspaceId: run.workspaceId, marketplace: run.provider, externalId: value.externalId } }, create: { workspaceId: run.workspaceId, marketplace: run.provider, externalId: value.externalId, name: value.name, description: value.description, canonicalUrl: value.canonicalUrl, price: value.price, currency: value.currency, rating: value.rating, reviewCount: value.reviewCount, salesCount: value.salesCount, sellerId: seller?.id ?? null, availability: value.availability, thumbnailUrl: value.images[0] ?? null, firstSeenAt: run.date, lastCheckedAt: run.date }, update: { name: value.name, description: value.description, canonicalUrl: value.canonicalUrl, price: value.price, currency: value.currency, rating: value.rating, reviewCount: value.reviewCount, salesCount: value.salesCount, sellerId: seller?.id ?? null, availability: value.availability, thumbnailUrl: value.images[0] ?? null, lastCheckedAt: run.date } });
        await tx.productCandidate.create({ data: { researchRunId: research.id, productId: product.id, marketplace: run.provider, externalId: value.externalId, sourceUrl: value.canonicalUrl, capturedData: json(candidate) } });
        await tx.productComparison.create({ data: { researchRunId: research.id, productId: product.id, position: index + 1, notes: `${candidate.comparisonGroup}: ${candidate.reasons.join(" ")}` } });
        if (candidate.score.score !== null) await tx.productScore.create({ data: { productId: product.id, score: candidate.score.score, confidence: candidate.score.confidence, availableFactors: [...candidate.score.availableFactors], missingFactors: [...candidate.score.missingFactors], factorScores: json(candidate.score.factorScores), explanation: candidate.score.explanation } });
      }
      return research;
    });
    return { ...run, id: saved.id };
  }
  async list(workspaceId: string): Promise<readonly SavedResearchRun[]> { const runs = await this.prisma.productResearchRun.findMany({ where: { workspaceId }, include: { candidates: true }, orderBy: { createdAt: "desc" } }); return runs.map(run => ({ id: run.id, workspaceId, date: run.completedAt ?? run.createdAt, queries: run.queries, categories: run.categories, candidates: run.candidates.map(value => value.capturedData as unknown as RankedCandidate), recommended: run.recommendedCount, opportunities: run.opportunityCount, rejected: run.rejectedCount, reasons: (run.reasons ?? {}) as Readonly<Record<string, readonly string[]>>, durationMs: run.durationMs ?? 0, provider: run.provider })); }
  async getCandidate(workspaceId: string, externalId: string) { const value = await this.prisma.productCandidate.findFirst({ where: { externalId, researchRun: { workspaceId } }, orderBy: { createdAt: "desc" } }); return value ? value.capturedData as unknown as RankedCandidate : null; }
  async setProductStatus(workspaceId: string, externalId: string, status: ProductStatus, reason: string) { const product = await this.prisma.product.findUnique({ where: { workspaceId_marketplace_externalId: { workspaceId, marketplace: "mercadolivre", externalId } } }); if (!product) throw new Error("product_not_found"); await this.prisma.$transaction(async tx => { await tx.product.update({ where: { id: product.id }, data: { status } }); await tx.auditLog.create({ data: { workspaceId, actorType: "owner", action: status === "under_review" ? "product.recommended_for_content" : "product.rejected", resourceType: "Product", resourceId: product.id, metadata: { reason, publicationApproved: false } } }); }); }
}
