import { createHash } from "node:crypto";
import type { EncryptedValue, TokenCipher } from "@casapratica/security";
import type { CapabilityMap } from "./capabilities.js";
import { createOAuthProof } from "./oauth.js";
import type { ProviderName } from "./provider.js";
import type { IntegrationProviderRegistry } from "./registry.js";

export type ConnectionStatus = "not_configured" | "disconnected" | "connecting" | "connected" | "error" | "token_expired";
export interface StoredConnection { id: string; workspaceId: string; provider: ProviderName; accessToken: EncryptedValue; refreshToken: EncryptedValue | null; expiresAt: Date; scopes: readonly string[]; status: ConnectionStatus }
export interface IntegrationRepository { list(workspaceId: string): Promise<readonly StoredConnection[]>; find(workspaceId: string, provider: ProviderName): Promise<StoredConnection | null>; save(connection: Omit<StoredConnection, "id">): Promise<StoredConnection>; saveCapabilities(accountId: string, capabilities: CapabilityMap): Promise<void>; disconnect(accountId: string): Promise<void> }
export interface OAuthStateRepository { save(value: { hash: string; workspaceId: string; provider: ProviderName; redirectUri: string; verifier: EncryptedValue; expiresAt: Date }): Promise<void>; consume(hash: string): Promise<{ workspaceId: string; provider: ProviderName; redirectUri: string; verifier: EncryptedValue; expiresAt: Date } | null> }
export interface PublicConnection { provider: ProviderName; status: ConnectionStatus; expiresAt: Date | null; capabilities?: CapabilityMap }
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
export class IntegrationService {
  constructor(private readonly providers: IntegrationProviderRegistry, private readonly accounts: IntegrationRepository, private readonly states: OAuthStateRepository, private readonly cipher: TokenCipher, private readonly redirectUris: Readonly<Record<ProviderName, string>>) {}
  async list(workspaceId: string): Promise<readonly PublicConnection[]> { const saved = new Map((await this.accounts.list(workspaceId)).map(account => [account.provider, toPublic(account)])); return (["pinterest", "facebook", "mercadolivre"] as const).map(provider => saved.get(provider) ?? { provider, status: this.providers.has(provider) ? "disconnected" : "not_configured", expiresAt: null }); }
  async status(workspaceId: string, provider: ProviderName): Promise<PublicConnection> { if (!this.providers.has(provider)) return { provider, status: "not_configured", expiresAt: null }; const account = await this.accounts.find(workspaceId, provider); return account ? toPublic(account) : { provider, status: "disconnected", expiresAt: null }; }
  async connect(workspaceId: string, provider: ProviderName) { const redirectUri = this.redirectUris[provider]; const proof = createOAuthProof(); await this.states.save({ hash: hash(proof.state), workspaceId, provider, redirectUri, verifier: this.cipher.encrypt(proof.codeVerifier), expiresAt: new Date(Date.now() + 10 * 60_000) }); return this.providers.get(provider).getAuthorizationUrl({ ...proof, redirectUri }).toString(); }
  async callback(provider: ProviderName, code: string, state: string) { const transaction = await this.states.consume(hash(state)); if (!transaction || transaction.provider !== provider || transaction.expiresAt <= new Date()) throw new Error("invalid_oauth_state"); const codeVerifier = this.cipher.decrypt(transaction.verifier); const tokens = await this.providers.get(provider).handleCallback(code, { state, codeVerifier, codeChallenge: "", redirectUri: transaction.redirectUri }); const capabilities = await this.providers.get(provider).getCapabilities(tokens.accessToken, tokens.scopes); const account = await this.accounts.save({ workspaceId: transaction.workspaceId, provider, accessToken: this.cipher.encrypt(tokens.accessToken), refreshToken: tokens.refreshToken ? this.cipher.encrypt(tokens.refreshToken) : null, expiresAt: tokens.expiresAt, scopes: tokens.scopes, status: "connected" }); await this.accounts.saveCapabilities(account.id, capabilities); return { provider, status: account.status, capabilities }; }
  async validate(workspaceId: string, provider: ProviderName) { const account = await this.required(workspaceId, provider); if (account.expiresAt <= new Date()) return { valid: false, status: "token_expired" as const }; return { valid: await this.providers.get(provider).validateConnection(this.cipher.decrypt(account.accessToken)), status: account.status }; }
  async refresh(workspaceId: string, provider: ProviderName) { const account = await this.required(workspaceId, provider); if (!account.refreshToken) throw new Error("refresh_token_unavailable"); const tokens = await this.providers.get(provider).refreshToken(this.cipher.decrypt(account.refreshToken)); await this.accounts.save({ ...account, accessToken: this.cipher.encrypt(tokens.accessToken), refreshToken: tokens.refreshToken ? this.cipher.encrypt(tokens.refreshToken) : account.refreshToken, expiresAt: tokens.expiresAt, scopes: tokens.scopes, status: "connected" }); return { provider, status: "connected" as const, expiresAt: tokens.expiresAt }; }
  async accessToken(workspaceId: string, provider: ProviderName) { const account = await this.required(workspaceId, provider); if (account.status !== "connected") throw new Error("integration_not_connected"); if (account.expiresAt <= new Date()) throw new Error("token_expired"); return this.cipher.decrypt(account.accessToken); }
  async disconnect(workspaceId: string, provider: ProviderName) { const account = await this.required(workspaceId, provider); await this.providers.get(provider).disconnect(this.cipher.decrypt(account.accessToken)); await this.accounts.disconnect(account.id); }
  private async required(workspaceId: string, provider: ProviderName) { const account = await this.accounts.find(workspaceId, provider); if (!account) throw new Error("integration_not_found"); return account; }
}
const toPublic = (account: StoredConnection): PublicConnection => ({ provider: account.provider, status: account.expiresAt <= new Date() ? "token_expired" : account.status, expiresAt: account.expiresAt });
