ALTER TABLE "ProductResearchRun"
ADD COLUMN "queries" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "categories" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "provider" TEXT NOT NULL DEFAULT 'mercadolivre',
ADD COLUMN "candidateCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "approvedCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "testCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "rejectedCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "reasons" JSONB,
ADD COLUMN "durationMs" INTEGER;
